### ISSUE TITLE
Do not use "import" in string representation of objects

### ISSUE THREAD

**Issue by aaronayres35** [enthought/mayavi#1002] opened 2021-01-13 15:12 UTC
We should not have "import" in this line:
https://github.com/enthought/mayavi/blob/61ef7c0eebbdca474b7cfdf6082bfc17fb5aaf59/tvtk/plugins/scene/ui/actions.py#L20-L23

instead we can simply have `'tvtk.plugins.scene.i_scene_manager.ISceneManager'`.  I am unsure if this is a one-off occurrence or if there are many other instances of this across the code base.

**Comment by rahulporuri** [comment] 2021-01-13 15:18
github seems to have glitched. closing as duplicate of #1001

**Closed by rahulporuri** 2021-01-13 15:18 UTC
