### ISSUE TITLE
Python crash while maximizing mayavi window

### ISSUE THREAD

**Issue by klonuo** [enthought/mayavi#55] opened 2012-12-21 20:55 UTC
For the record, I run latest git mayavi on Windows XP, Python 2.7 with Qt enabled.

I was running this example code: http://gael-varoquaux.info/blog/wp-content/uploads/2009/04/delaunay_py and it shows fine. But if I try to maximize mayavi window or go fullscreen, python crashes - I get MS visual C++ runtime error about python.exe process. Terminal writes this:

>Qt has caught an exception thrown from an event handler. Throwing
>exceptions from an event handler is not supported in Qt. You must
>reimplement QApplication::notify() and catch all exceptions there.
>
>QWidget::repaint: Recursive repaint detected

**Comment by stefanoborini** [comment] 2016-04-21 14:44
@dpinte do we still support XP?

**Comment by stefanoborini** [comment] 2016-04-21 14:45
probably no longer relevant (it's 4 years old), but verifying on windows 7 and mayavi 4.4.4.

**Comment by stefanoborini** [comment] 2016-04-21 14:56
Checked on windows 7. Cannot reproduce.

**Comment by stefanoborini** [comment] 2016-04-28 09:07
Closing. No longer relevant

**Closed by stefanoborini** 2016-04-28 09:07 UTC
