### ISSUE TITLE
troubles installing mayavi in Anaconda 3.6

### ISSUE THREAD

**Issue by mafaldadias** [enthought/mayavi#625] opened 2018-03-28 07:41 UTC
Hi, I have a recent install of Anaconda and I am trying to install Mayavi without success. I have MacOS High Sierra and i am using Python 3.6. 

When using 

```$ conda install -c anaconda mayavi ```

I run into the problem:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - mayavi
  - traitlets
Use "conda info <package>" to see the dependencies for each package.
```

So I tried to install it directly using pip. I read I needed to instal setuptools and vkt first, so I did it by
```
$ conda install -c conda-forge setuptools 
$ conda install -c clinicalgraphics vtk 
```

But when I try to install mayavi with pip I still run into problems:
```
$ pip install mayavi
Collecting mayavi
  Using cached mayavi-4.5.0.tar.bz2
Requirement already satisfied: apptools in /anaconda3/lib/python3.6/site-packages (from mayavi)
Requirement already satisfied: traits in /anaconda3/lib/python3.6/site-packages (from mayavi)
Requirement already satisfied: traitsui in /anaconda3/lib/python3.6/site-packages (from mayavi)
Requirement already satisfied: configobj in /anaconda3/lib/python3.6/site-packages (from apptools->mayavi)
Requirement already satisfied: pyface in /anaconda3/lib/python3.6/site-packages (from traitsui->mayavi)
Requirement already satisfied: six in /anaconda3/lib/python3.6/site-packages (from configobj->apptools->mayavi)
Requirement already satisfied: pygments in /anaconda3/lib/python3.6/site-packages (from pyface->traitsui->mayavi)
Building wheels for collected packages: mayavi
  Running setup.py bdist_wheel for mayavi ... error
  Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/wp/l3j6c2k1
7jz8t8k78l7ct9km0005cr/T/pip-build-57ou1emg/mayavi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r

\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/wp/l3j6c2k17jz8t8k78l7ct9km0005cr/T/tmpq6b
cxzqopip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  Fatal Python error: PyThreadState_Get: no current thread


  ----------------------------------------
  Failed building wheel for mayavi
  Running setup.py clean for mayavi
Failed to build mayavi
Installing collected packages: mayavi
  Running setup.py install for mayavi ... error
    Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/wp/l3j6c2
k17jz8t8k78l7ct9km0005cr/T/pip-build-57ou1emg/mayavi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('
\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/wp/l3j6c2k17jz8t8k78l7ct9km0005cr/T/pi
p-d2sq055y-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Fatal Python error: PyThreadState_Get: no current thread
```

It seems like the problem is related to setup.py but I don't understand because I just installed setuptools. Any ideas? Thank you very much!

**Comment by jonnyfrazer** [comment] 2018-04-03 19:40
I am having exactly the same problem.

**Comment by jonnyfrazer** [comment] 2018-04-03 19:57
Maybe it is simply that Mayavi is not compatible with python 3. I found this [stackoverflow thread from a few years ago](https://stackoverflow.com/questions/19138418/get-mayavi-working-with-python-3?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).

**Comment by jonnyfrazer** [comment] 2018-04-05 15:04
@jonathanrocher thanks for your help. I tried following the "Installing from Conda" section. I then created a new IPython kernel:

    source activate pyconda
    conda install pip
    conda install ipykernel
    python -m ipykernel install --user --name pyconda --display-name "Python (pyconda)"

Then if I now open a Jupyter notebook, switch to the Python (pyconda) kernel and try to evaluate 

    from mayavi import mlab

I get a message saying the kernel has died, then shortly after that python shuts down. Any idea what I might have done wrong?

**Comment by jonathanrocher** [comment] 2018-04-05 15:33
@jonnyfrazer 
1. That seems unrelated to the original issue, and should be discussed elsewhere
2. No idea why it might crash, there could be many reasons. The manual creation of ipython kernel as opposed to just launching ipython worries me. Can you try to just launch ipython and import mlab in there? Same issue? Any more details you can glean about the issue (traceback, log, ...)?

**Comment by jonnyfrazer** [comment] 2018-04-05 15:47
@jonathanrocher 

Just to clarify. Initially, I had exactly the same problem as @mafaldadias but that was when I tried to install mayavi without first creating a conda environment. I then tried following your instructions and ran into this new problem. 

So now I just tried the following

    $ source activate pyconda
    $ ipython

    In [1]: from mayavi import mlab

and I get

    Fatal Python error: PyThreadState_Get: no current thread
    Abort trap: 6

Should I start a new issue? Sorry, I'm very new to all this.

**Comment by jonathanrocher** [comment] 2018-04-05 15:53
No apologies needed. Thanks for the additional details. Now we know the crash is still likely to be related to the original issue, and is therefore appropriate to keep it here. I have no idea what could be the cause of the underlying issue, and I need to leave it to Mayavi experts now...

**Comment by larsoner** [comment] 2018-05-02 19:41
This looks like a dup of #552

**Comment by prabhuramachandran** [comment] 2018-08-26 21:12
I am closing this now as things seem to have improved a lot now.

**Closed by prabhuramachandran** 2018-08-26 21:12 UTC
