### ISSUE TITLE
How to run Mayavi on Python 3.6.5 as Pyside is not supported in versions of Python ulterior to 3.4

### ISSUE THREAD

**Issue by bjce** [enthought/mayavi#655] opened 2018-06-16 20:22 UTC
I'm trying to run the file 'mri.py' provided on the [mayavi's gallery](https://docs.enthought.com/mayavi/mayavi/auto/examples.html)

I'm running on 
MacOs 10.13.4
Python 3.6.5
and have the followint packages installed:
```
vtk==8.1.0
traitsui==6.0.0
PySide2==5.9.0a1.dev1525348214
PyQt5==5.10.1
```

When trying to run the script, I get the following error message `ModuleNotFoundError: No module named 'PySide'`

Unfortunately PySide is only supported for version of Python ulterior to 3.4  as stated the error message of the command `pip install PySide`:

```
Collecting PySide
  Using cached https://files.pythonhosted.org/packages/36/ac/ca31db6f2225844d37a41b10615c3d371587677efd074db29855e7035de6/PySide-1.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-sc9zy9ia/PySide/
```

I would like to use mayavi which look like an awesome package, but I don't want to have to dangerously downgrade to Python 3.4 as well as downgrading all the corresponding packages

I already tried the following as pointed out in [#595](https://github.com/enthought/mayavi/issues/595)

```
 export ETS_TOOLKIT=qt4
 export QT_API=pyqt5
```

Here are the piece of code I ran which doesn't run in Atom/Hydrogen but works in Spyder

```
"""
Viewing MRI data with cut plane and iso surface.

This example downloads an MRI scan, turns it into a 3D numpy array and
visualizes it.

First we extract some internal structures of the brain by defining a
volume of interest around them, and using iso surfaces.

Then we display two cut planes to show the raw MRI data itself.

Finally we display the outer surface, but we restrict it to volume of
interest to leave a cut for the cut planes.

For an example of feature extraction from MRI data using Mayavi and vtk,
see :ref:`example_tvtk_segmentation`.
"""


### Download the data, if not already on disk #################################
import os
if not os.path.exists('MRbrain.tar.gz'):
    # Download the data
    try:
        from urllib import urlopen
    except ImportError:
        from urllib.request import urlopen
    print("Downloading data, Please Wait (7.8MB)")
    opener = urlopen(
                'http://graphics.stanford.edu/data/voldata/MRbrain.tar.gz')
    open('MRbrain.tar.gz', 'wb').write(opener.read())

# Extract the data
import tarfile
tar_file = tarfile.open('MRbrain.tar.gz')
try:
    os.mkdir('mri_data')
except:
    pass
tar_file.extractall('mri_data')
tar_file.close()


### Read the data in a numpy 3D array #########################################
import numpy as np
data = np.array([np.fromfile(os.path.join('mri_data', 'MRbrain.%i' % i),
                                        dtype='>u2') for i in range(1, 110)])
data.shape = (109, 256, 256)
data = data.T

# Display the data ############################################################
from mayavi import mlab

mlab.figure(bgcolor=(0, 0, 0), size=(400, 400))

src = mlab.pipeline.scalar_field(data)
# Our data is not equally spaced in all directions:
src.spacing = [1, 1, 1.5]
src.update_image_data = True


# Extract some inner structures: the ventricles and the inter-hemisphere
# fibers. We define a volume of interest (VOI) that restricts the
# iso-surfaces to the inner of the brain. We do this with the ExtractGrid
# filter.
blur = mlab.pipeline.user_defined(src, filter='ImageGaussianSmooth')
voi = mlab.pipeline.extract_grid(blur)
voi.trait_set(x_min=125, x_max=193, y_min=92, y_max=125, z_min=34, z_max=75)

mlab.pipeline.iso_surface(voi, contours=[1610, 2480], colormap='Spectral')

# Add two cut planes to show the raw MRI data. We use a threshold filter
# to remove cut the planes outside the brain.
thr = mlab.pipeline.threshold(src, low=1120)
cut_plane = mlab.pipeline.scalar_cut_plane(thr,
                                plane_orientation='y_axes',
                                colormap='black-white',
                                vmin=1400,
                                vmax=2600)
cut_plane.implicit_plane.origin = (136, 111.5, 82)
cut_plane.implicit_plane.widget.enabled = False

cut_plane2 = mlab.pipeline.scalar_cut_plane(thr,
                                plane_orientation='z_axes',
                                colormap='black-white',
                                vmin=1400,
                                vmax=2600)
cut_plane2.implicit_plane.origin = (136, 111.5, 82)
cut_plane2.implicit_plane.widget.enabled = False

# Extract two views of the outside surface. We need to define VOIs in
# order to leave out a cut in the head.
voi2 = mlab.pipeline.extract_grid(src)
voi2.trait_set(y_min=112)
outer = mlab.pipeline.iso_surface(voi2, contours=[1776, ],
                                        color=(0.8, 0.7, 0.6))

voi3 = mlab.pipeline.extract_grid(src)
voi3.trait_set(y_max=112, z_max=53)
outer3 = mlab.pipeline.iso_surface(voi3, contours=[1776, ],
                                         color=(0.8, 0.7, 0.6))


mlab.view(-125, 54, 326, (145.5, 138, 66.5))
mlab.roll(-175)

mlab.show()

import shutil
shutil.rmtree('mri_data')
```

I get the following error message (in Atom/Hydrogen): 

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-4966758d9cbc> in <module>()
     50 
     51 # Display the data ############################################################
---> 52 from mayavi import mlab
     53 
     54 mlab.figure(bgcolor=(0, 0, 0), size=(400, 400))

/anaconda3/lib/python3.6/site-packages/mayavi/mlab.py in <module>()
     13 
     14 # Mayavi imports
---> 15 from mayavi.tools.camera import view, roll, yaw, pitch, move
     16 from mayavi.tools.figure import figure, clf, gcf, savefig, \
     17     draw, sync_camera, close, screenshot

/anaconda3/lib/python3.6/site-packages/mayavi/tools/camera.py in <module>()
     22 # We can't use gcf, as it creates a circular import in camera management
     23 # routines.
---> 24 from .engine_manager import get_engine
     25 
     26 

/anaconda3/lib/python3.6/site-packages/mayavi/tools/engine_manager.py in <module>()
     12 from mayavi.preferences.api import preference_manager
     13 from mayavi.core.registry import registry
---> 14 from mayavi.core.engine import Engine
     15 from mayavi.core.off_screen_engine import OffScreenEngine
     16 from mayavi.core.null_engine import NullEngine

/anaconda3/lib/python3.6/site-packages/mayavi/core/engine.py in <module>()
     32 from mayavi.core.adder_node import AdderNode, SceneAdderNode
     33 from mayavi.preferences.api import preference_manager
---> 34 from mayavi.core.ui.mayavi_scene import viewer_factory
     35 
     36 

/anaconda3/lib/python3.6/site-packages/mayavi/core/ui/mayavi_scene.py in <module>()
     10 
     11 # Enthought library imports
---> 12 from tvtk.tools.ivtk import IVTK
     13 from tvtk.pyface.api import DecoratedScene
     14 from traits.api import Callable

/anaconda3/lib/python3.6/site-packages/tvtk/tools/ivtk.py in <module>()
     33 from pyface.api import SplitApplicationWindow, ApplicationWindow
     34 from pyface.api import SplitPanel
---> 35 from tvtk.pyface.api import Scene, DecoratedScene
     36 from pyface.action.api import Action, MenuBarManager,\
     37      MenuManager, Separator

/anaconda3/lib/python3.6/site-packages/tvtk/pyface/api.py in <module>()
----> 1 from .decorated_scene import DecoratedScene
      2 from .scene import Scene

/anaconda3/lib/python3.6/site-packages/tvtk/pyface/decorated_scene.py in <module>()
     11 # Import the toolkit specific version.
     12 from tvtk.pyface.toolkit import toolkit_object
---> 13 DecoratedScene = toolkit_object('decorated_scene:DecoratedScene')

/anaconda3/lib/python3.6/site-packages/pyface/base_toolkit.py in __call__(self, name)
    142         for package in self.packages:
    143             try:
--> 144                 module = import_module(mname, package)
    145             except ImportError as exc:
    146                 # is the error while trying to import package mname or not?

/anaconda3/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/anaconda3/lib/python3.6/site-packages/tvtk/pyface/ui/qt4/decorated_scene.py in <module>()
     21 
     22 # Local imports.
---> 23 from .scene import Scene, popup_save
     24 
     25 

/anaconda3/lib/python3.6/site-packages/tvtk/pyface/ui/qt4/scene.py in <module>()
     38 from tvtk.pyface.tvtk_scene import TVTKScene
     39 
---> 40 from .QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
     41 
     42 

/anaconda3/lib/python3.6/site-packages/tvtk/pyface/ui/qt4/QVTKRenderWindowInteractor.py in <module>()
     81     if QVTKRWIBase == "QGLWidget":
     82         from PySide.QtOpenGL import QGLWidget
---> 83     from PySide.QtGui import QWidget, QSizePolicy, QApplication, QWheelEvent
     84     from PySide.QtCore import Qt, QTimer, QObject, QSize, QEvent
     85 else:

ModuleNotFoundError: No module named 'PySide'
```

Interestingly, when I run the `import PySide` in BOTH Atom/Hydrogen and Spyder it doesn't work:

- Spyder: 

```
import PySide
Traceback (most recent call last):

  File "<ipython-input-1-3267ca000ac0>", line 1, in <module>
    import PySide

ModuleNotFoundError: No module named 'PySide'
```
- Atom/Hydrogen
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-d541f2414490> in <module>()
----> 1 import pyside

ModuleNotFoundError: No module named 'pyside'
```

As the script `mri.py` runs without problem in Spyder, It seems that Spyder uses a workaround which is not present in Atom/Hydrogen

**Comment by prabhuramachandran** [comment] 2018-06-17 15:43
You should use pyqt5 on Python 3.6 as discussed here: https://github.com/enthought/mayavi#installation
This is really not an issue with Mayavi per-se, so am closing this.  Please reopen if this is not resolved if you install pyqt5.  You should be able to pip install pyqt5.

**Comment by bjce** [comment] 2018-06-17 15:51
Thank you for your feedback @prabhuramachandran.

As stated in the beginning of the message, pyqt5 is already installed. I still ran the command `$ pip install PyQt5` and `pip install pyqt5`. Both give me the same message:

```
Requirement already satisfied: PyQt5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (5.10.1)
Requirement already satisfied: sip<4.20,>=4.19.4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from PyQt5) (4.19.8)
```

**Comment by prabhuramachandran** [comment] 2018-06-17 16:10
Sorry about that.  Not sure what is going on but can you try uninstalling pyside2 and see if that helps?  I am using python 3.6, pyqt5, and Mayavi on OSX and it works fine.

**Comment by bjce** [comment] 2018-06-17 16:31
Thank you again @prabhuramachandran 

I uninstalled PySide2 and indeed this time it works. The problem is that I wrote another GUI with PySide2 and on the long term I would like to continue to use PySide2 for those 2 reasons:
- Although it's very similar to PyQt5, there are still some slight differences between PyQt5 and PySide2
- Copyright problem if you want to diffuse on a larger scale an application written with PyQt5.
The last solution is to install/uninstall PyQt5/PySide2 alternatively but this to my opinion not viable on the long term. 

Do you have another idea?

**Comment by prabhuramachandran** [comment] 2018-06-17 16:50
PySide2 support is still experimental with Traits/Pyface etc.  I think Mayavi itself ought to be compatible but the rest of the ETS stack will need to properly support PySide.  @corranwebster -- thoughts?

**Comment by prabhuramachandran** [comment] 2018-06-17 18:47
Hmm, see this PR, maybe pyside2 does already work for the most part.  
https://github.com/enthought/pyface/pull/318/files
I think you need to set QT_API to pyside2.  Try that and see if it works.

**Comment by bjce** [comment] 2018-06-18 07:18
Thank you for your answer @prabhuramachandran 

So I added the line `os.environ['QT_API'] = 'pyside2'` to the file `mri.py`

I replaced those lines:
```
### Download the data, if not already on disk #################################
import os
if not os.path.exists('MRbrain.tar.gz'):
```
by those lines:
```
### Download the data, if not already on disk #################################
import os
os.environ['QT_API'] = 'pyside2'
if not os.path.exists('MRbrain.tar.gz'):
```

but unfortunately I still get `ModuleNotFoundError: No module named 'PySide'`

**Comment by corranwebster** [comment] 2018-06-18 08:46
Yes, Pyside2 support for TraitsUI and Pyface is currently very experimental (the tests currently fail spectacularly) but given that PyQt5 works and Pyside2 is nominally API compatible then it may end up being OK despite the tests failing.

@prabhuramachandran It looks like part of the problem is that `tvtk/pyface/ui/qt4` doesn't have an appropriate branch for PySide2, for when `QT_API=pyside2` (probably something needed here https://github.com/enthought/mayavi/blob/master/tvtk/pyface/ui/qt4/QVTKRenderWindowInteractor.py#L50 and https://github.com/enthought/mayavi/blob/master/tvtk/pyface/ui/qt4/QVTKRenderWindowInteractor.py#L85 (the code will probably look like the PyQt5 code, but import from Pyside2)

**Comment by bjce** [comment] 2018-06-18 08:55
thank you for your comment @corranwebster

**Comment by prabhuramachandran** [comment] 2018-08-26 21:03
Pyside2 is now fully supported as of 4.6.2, so am closing this for now.

**Closed by prabhuramachandran** 2018-08-26 21:03 UTC

**Comment by ManPython** [comment] 2021-12-07 21:47
@prabhuramachandran any simple example to run mayavi and PySide2 ?
