### ISSUE TITLE
another "from mayavi import mlab" error

### ISSUE THREAD

**Issue by worrallj** [enthought/mayavi#817] opened 2019-08-19 19:03 UTC
Hi I can see that there are several people who run into problems with this command, but none of the other issues seemed to address this for me. 

I'm using python 3.7 (.3150.1013, if that matters) anaconda installation.

I installed mayavi 4.6.2 via the anaconda navigator GUI package manager.

I'm attempting to run from a script in Spyder. I get the following traceback when I try to run 

```python
from mayavi import mlab
```

```python
runfile('C:/Users/ensif/.spyder-py3/temp.py', wdir='C:/Users/ensif/.spyder-py3')
Traceback (most recent call last):

  File "D:\programs\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-11-2363db0b26bb>", line 1, in <module>
    runfile('C:/Users/ensif/.spyder-py3/temp.py', wdir='C:/Users/ensif/.spyder-py3')

  File "D:\programs\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\programs\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ensif/.spyder-py3/temp.py", line 8, in <module>
    from mayavi import mlab

  File "D:\programs\Anaconda\lib\site-packages\mayavi\mlab.py", line 15, in <module>
    from mayavi.core.common import process_ui_events

  File "D:\programs\Anaconda\lib\site-packages\mayavi\core\common.py", line 16, in <module>
    from apptools.persistence.state_pickler import create_instance

  File "D:\programs\Anaconda\lib\site-packages\apptools\persistence\state_pickler.py", line 1210
    
    ^
SyntaxError: invalid syntax
```

I can just import mayavi directly, but then when I try to use mlab I get a different error:
```python
# Create the data.
from numpy import pi, sin, cos, mgrid
dphi, dtheta = pi/250.0, pi/250.0
[phi,theta] = mgrid[0:pi+dphi*1.5:dphi,0:2*pi+dtheta*1.5:dtheta]
m0 = 4; m1 = 3; m2 = 2; m3 = 3; m4 = 6; m5 = 2; m6 = 6; m7 = 4;
r = sin(m0*phi)**m1 + cos(m2*phi)**m3 + sin(m4*theta)**m5 + cos(m6*theta)**m7
x = r*sin(phi)*cos(theta)
y = r*cos(phi)
z = r*sin(phi)*sin(theta)

# View it.
import mayavi
s = mayavi.mlab.mesh(x, y, z)
mayavi.mlab.show()
```

```python
runfile('C:/Users/ensif/.spyder-py3/temp.py', wdir='C:/Users/ensif/.spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-12-2363db0b26bb>", line 1, in <module>
    runfile('C:/Users/ensif/.spyder-py3/temp.py', wdir='C:/Users/ensif/.spyder-py3')

  File "D:\programs\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\programs\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ensif/.spyder-py3/temp.py", line 20, in <module>
    s = mayavi.mlab.mesh(x, y, z)

AttributeError: module 'mayavi' has no attribute 'mlab'
```

Thank you and let me know if there's further detail I can provide!
Jason

**Comment by jpmorr** [comment] 2019-08-20 09:31
Exact same problem, although installed via conda. Conda has been a bit broken lately and a recent package install causes a host of packages to be upgraded and downgraded on my system, which I think has contributed to the issue as I had happily been using mayavi 4.7.1 for many month. No idea how to resolve this yet.

**Comment by dhammo2** [comment] 2019-09-18 14:12
In this file (D:\programs\Anaconda\lib\site-packages\apptools\persistence\state_pickler.py) some lines use '\' characters to split logical actions.

Since you're using anaconda if you use the Spyder IDE it will automatically flag the problem lines.

Remove these '\' characters and put everything on the same line for the if conditions.

**Comment by prabhuramachandran** [comment] 2019-10-05 04:18
I have no idea why this is happening, the original source does not have the new lines, and neither do the source tarballs on pypi.  I have sent a PR here to address the long line continuation but this is not really fixing the actual issue: https://github.com/enthought/apptools/pull/98

**Comment by rahulporuri** [comment] 2019-10-08 14:01
@prabhuramachandran apptools 4.4.0 is the latest release (which is very old) and IIRC, 4.4.0 used `2to3` so it's possible that the issue isn't the line continuation. I'll try installing locally and see what happens.

**Comment by rahulporuri** [comment] 2019-10-08 14:05
there's definitely something funny going on here. i installed apptools and mayavi from pip into a python 3.6 environment and the line count of the `state_pickler` file is 1037. The traceback reports that the issue is in line 1210.

Testing with python 3.7 now.

**Comment by mdickinson** [comment] 2019-10-08 14:36
https://bugs.python.org/issue34108 seems likely to be the cause of the issue

**Comment by mdickinson** [comment] 2019-10-08 14:41
That bug should be fixed in Python 3.7.1. @worrallj Are you on Python 3.7.0?

**Comment by Alex-AMC** [comment] 2019-12-05 16:11
I am still getting the exact same problem in Python 3.7.5

**Comment by mdickinson** [comment] 2019-12-05 16:16
@Alex-AMC What apptools version do you have, and how did you install it? The most recent release (apptools 4.5.0) should be immune from this problem, since it's no longer based on 2to3. Earlier versions could still have the issue if they're being installed from a local `pip` cache (since the 2to3 conversion could have occurred with an older Python version), or if they're coming from some other package provider (if that provider used an older Python to package apptools).

**Comment by generalpeng26** [comment] 2019-12-24 06:53
I have the same problem. Does anyone know how to solve this problem? 
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-4-05cbf3aac7af>", line 1, in <module>
    from mayavi import mlab

  File "C:\ProgramData\Anaconda3\lib\site-packages\mayavi\mlab.py", line 15, in <module>
    from mayavi.core.common import process_ui_events

  File "C:\ProgramData\Anaconda3\lib\site-packages\mayavi\core\common.py", line 16, in <module>
    from apptools.persistence.state_pickler import create_instance

  File "C:\ProgramData\Anaconda3\lib\site-packages\apptools\persistence\state_pickler.py", line 1210
    
    ^
SyntaxError: invalid syntax

**Comment by prabhuramachandran** [comment] 2019-12-24 18:32
what is the version of apptools you have installed?  How did you install this?  Can you try `pip install -U apptools`?  or even better `pip install -U --no-cache-dir apptools`?

**Comment by mdickinson** [comment] 2020-01-02 09:37
I think we should close here; there's no Mayavi bug (or apptools bug). This may be an issue with conda builds, in which case it should be reported to anaconda.

**Closed** 2020-01-08 09:22 UTC

**Comment by gloryVine** [comment] 2020-08-30 03:59
This is not an anaconda bug. I am not using anaconda, and I installed via the 'bleeding edge' instructions on the GitHub page, because the pip install didn't work for me (it wasn't able to build).
Now, doing 
`import mayavi` works,
but trying to use `mayavi.mlab` or `from mayavi import mlab` both give `
AttributeError: module 'mayavi' has no attribute 'mlab'`.

**Comment by mdickinson** [comment] 2020-09-01 07:04
@gloryVine It's probably best to open a new issue. There were multiple issues reported in the original description, but the investigations here focused on the `SyntaxError` from `apptools`. It sounds as though you're seeing something different.
