### ISSUE TITLE
Does Mayavi support PyQt5?

### ISSUE THREAD

**Issue by Felix-neko** [enthought/mayavi#595] opened 2018-02-01 23:19 UTC
Hi all!

I want to embed a `mayavi` surface plot into a PyQt5 widget, like I did with matplotlib plots. Alas, I didn't find any working examples of such an embedding.

Is PyQt5 supported now?

**Comment by mpanighel** [comment] 2018-02-18 12:04
Since https://github.com/enthought/mayavi/pull/597 PyQt5 should be supported.

However I had no luck in making mayavi work with it on Linux (mainly for my little knowledge of python); most probably I just missing something obvious (package).
I setup a fresh python 3.6.4 environment (Kubuntu 14.04) with pyqt 5.10, vtk 8.1.0, traits 4.6.0 and traitsui 5.1.0 (a complete list of packages is [here](https://github.com/enthought/mayavi/files/1734663/pip_list.txt)). Launching mayavi2 (installed from the latest pull) gives `ImportError: Could not import backend for traits`. Required TraitsBackendWx or TraitsBackendQt are no longer available/supported with such configuration.

**Comment by prabhuramachandran** [comment] 2018-02-18 18:05
@mpanighel -- functional Qt5 support existed from #528 but there have been many bugs fixed in #597.  It is possible that you need to set the right ETS_TOOLKIT, I am not sure, try this:
```
 export ETS_TOOLKIT=qt4
 export QT_API=pyqt5
```
Now this may require the master version of pyface, and traitsui.

**Comment by mpanighel** [comment] 2018-02-19 09:23
>> functional Qt5 support existed from #528

Sure, sorry!

>> It is possible that you need to set the right ETS_TOOLKIT, I am not sure, try this

I tried something like that but it complains that valid api are just `pyside` or `pyqt`, I think I have something wrong with the configuration of qt5 itself; I will look into it myself. Thank you again!

**Comment by prabhuramachandran** [comment] 2018-02-19 13:42
@mpanighel -- sorry, no need to apologize.  I just mentioned that so folks who see the ticket do not get the wrong idea. Anyway, it is likely that you may need pyface/traitsui from master too, can you see if that helps.  That said, I believe there will be a new release of those on pypi soon (O(week)).

**Comment by mpanighel** [comment] 2018-02-19 15:16
Thanks @prabhuramachandran ! Mayavi works upgrading to master pyface (5.2.0) and traitsui (5.2.0) and setting:
```
export ETS_TOOLKIT=qt4
export QT_API=pyqt5
```

**Comment by fpavogt** [comment] 2018-03-14 14:01
Hi all. Quick update in case anyone (like me) stumbles on this. Running Mac OSX and Anaconda3.6, mayavi (installed from its current master Github repo) does still work with/require pyface (5.2.0) and traitsui (5.2.0), both installed from their respective master Github repos, and vtk 8.1.0 installed with pip.

Thanks @prabhuramachandran for all your efforts! It will be real nice when all these eventually get pushed to pypi (this very useful thread took me a while to dig up).

**Comment by Instinctlol** [comment] 2018-03-28 12:52
Thanks fpavogt, this works for windows 10 as well.

- pip install vtk pygments
- Download traits, traitsui, pyface, mayavi master repos
- easy_install all of them

**Comment by xaverm** [comment] 2018-04-08 19:58
Hi **@fpavogt**: would you please be so kind as to help me a little more, on how to get this to work? Within my py36 environment I did 
```
git clone https://github.com/enthought/mayavi.git
git clone https://github.com/enthought/pyface.git
git clone https://github.com/enthought/traitsui.git
```
then, within each of the respective directories, I did `python setup.py install`, which gave me packages of type, e.g.:
```
conda list | grep pyfa
mayavi                    4.5.1.dev0                <pip>
pyface                    5.2.0.dev347              <pip>
traitsui                  5.2.0.dev420              <pip>
```
for all three, mayavi, pyface, and traitsui.
However simple `from mayavi import mlab` within an ipython console will fail with errors
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-67847bc6bfd0> in <module>()
----> 1 from mayavi import mlab

~/.anaconda3/envs/py36/lib/python3.6/site-packages/mayavi-4.5.1.dev0-py3.6-linux-x86_64.egg/mayavi/mlab.py in <module>()
     25 
     26 # Mayavi imports
---> 27 from mayavi.tools.camera import view, roll, yaw, pitch, move
     28 from mayavi.tools.figure import figure, clf, gcf, savefig, \
     29     draw, sync_camera, close, screenshot

~/.anaconda3/envs/py36/lib/python3.6/site-packages/mayavi-4.5.1.dev0-py3.6-linux-x86_64.egg/mayavi/tools/camera.py in <module>()
     22 # We can't use gcf, as it creates a circular import in camera management
     23 # routines.
---> 24 from .engine_manager import get_engine
     25 
     26 

~/.anaconda3/envs/py36/lib/python3.6/site-packages/mayavi-4.5.1.dev0-py3.6-linux-x86_64.egg/mayavi/tools/engine_manager.py in <module>()
     12 from mayavi.preferences.api import preference_manager
     13 from mayavi.core.registry import registry
---> 14 from mayavi.core.engine import Engine
     15 from mayavi.core.off_screen_engine import OffScreenEngine
     16 from mayavi.core.null_engine import NullEngine

~/.anaconda3/envs/py36/lib/python3.6/site-packages/mayavi-4.5.1.dev0-py3.6-linux-x86_64.egg/mayavi/core/engine.py in <module>()
     26 # Local imports.
     27 from tvtk.common import is_old_pipeline
---> 28 from mayavi.core.base import Base
     29 from mayavi.core.scene import Scene
     30 from mayavi.core.common import error, process_ui_events

~/.anaconda3/envs/py36/lib/python3.6/site-packages/mayavi-4.5.1.dev0-py3.6-linux-x86_64.egg/mayavi/core/base.py in <module>()
     28 from tvtk.common import is_old_pipeline
     29 from mayavi.preferences.api import preference_manager
---> 30 from mayavi.core.common import get_engine
     31 
     32 # Setup a logger for this module.

~/.anaconda3/envs/py36/lib/python3.6/site-packages/mayavi-4.5.1.dev0-py3.6-linux-x86_64.egg/mayavi/core/common.py in <module>()
     19     pyface = None
     20 else:
---> 21     from pyface import api as pyface
     22 
     23 # Setup a logger for this module.

~/.anaconda3/envs/py36/lib/python3.6/site-packages/pyface-5.2.0.dev347-py3.6.egg/pyface/api.py in <module>()
     33 from .progress_dialog import ProgressDialog
     34 from .python_editor import PythonEditor
---> 35 from .python_shell import PythonShell
     36 from .sorter import Sorter
     37 from .single_choice_dialog import choose_one, SingleChoiceDialog

~/.anaconda3/envs/py36/lib/python3.6/site-packages/pyface-5.2.0.dev347-py3.6.egg/pyface/python_shell.py in <module>()
     19 
     20 from .toolkit import toolkit_object
---> 21 PythonShell = toolkit_object('python_shell:PythonShell')
     22 
     23 #### EOF ######################################################################

~/.anaconda3/envs/py36/lib/python3.6/site-packages/pyface-5.2.0.dev347-py3.6.egg/pyface/base_toolkit.py in __call__(self, name)
    142         for package in self.packages:
    143             try:
--> 144                 module = import_module(mname, package)
    145             except ImportError as exc:
    146                 # is the error while trying to import package mname or not?

~/.anaconda3/envs/py36/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

~/.anaconda3/envs/py36/lib/python3.6/site-packages/pyface-5.2.0.dev347-py3.6.egg/pyface/ui/qt4/python_shell.py in <module>()
     29 # Local imports.
     30 from .code_editor.pygments_highlighter import PygmentsHighlighter
---> 31 from .console.api import BracketMatcher, CallTipWidget, CompletionLexer, \
     32     HistoryConsoleWidget
     33 from pyface.i_python_shell import IPythonShell, MPythonShell

~/.anaconda3/envs/py36/lib/python3.6/site-packages/pyface-5.2.0.dev347-py3.6.egg/pyface/ui/qt4/console/api.py in <module>()
      2 from .call_tip_widget import CallTipWidget
      3 from .completion_lexer import CompletionLexer
----> 4 from .console_widget import ConsoleWidget
      5 from .history_console_widget import HistoryConsoleWidget

~/.anaconda3/envs/py36/lib/python3.6/site-packages/pyface-5.2.0.dev347-py3.6.egg/pyface/ui/qt4/console/console_widget.py in <module>()
     34 #-----------------------------------------------------------------------------
     35 
---> 36 class ConsoleWidget(QtGui.QWidget):
     37     """ An abstract base class for console-type widgets. This class has
     38         functionality for:

~/.anaconda3/envs/py36/lib/python3.6/site-packages/pyface-5.2.0.dev347-py3.6.egg/pyface/ui/qt4/console/console_widget.py in ConsoleWidget()
    107     _shortcuts = set(_ctrl_down_remap.keys() +
    108                      [ QtCore.Qt.Key_C, QtCore.Qt.Key_G, QtCore.Qt.Key_O,
--> 109                        QtCore.Qt.Key_V ])
    110 
    111     #---------------------------------------------------------------------------

TypeError: unsupported operand type(s) for +: 'dict_keys' and 'list'
```

What am I doing wrong?
Xaver

PS: setting
```
export ETS_TOOLKIT=qt4
export QT_API=pyqt5
```
on install and on running the ipython shell does not help.

**Comment by prabhuramachandran** [comment] 2018-04-08 20:07
Looks like a 2to3 problem with some stale files.  Can you pip uinstall pyface.  Then inside the pyface directory do an `rm -rf build` and then run `setup.py install` again.  I am not sure why but for some reason 2to3 has not been run while generating this egg.  Did you install this on python2.x at some point?

**Comment by xaverm** [comment] 2018-04-08 20:35
I'm sorry, in which pyface directory should I rm -rf ?

**Comment by prabhuramachandran** [comment] 2018-04-09 03:40
From the directory you cloned, the pyface source directory.  2to3 runs on the pyface codebase before the package is installed.

**Comment by xaverm** [comment] 2018-04-09 06:55
Ok. Did that for all three packages: mayavi, pyface, and traitsui. Now:

## 1)
in a simple IPython console within an Anaconda Python 3.6 environment I get
```
In [1]: from mayavi import mlab
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/temporary/mayavi/mayavi/tvtk/tvtk_classes.zip/tvtk_classes/tvtk_helper.pyc in get_module(fname)

ModuleNotFoundError: No module named 'tvtk.custom.light'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-67847bc6bfd0> in <module>()
----> 1 from mayavi import mlab

~/temporary/mayavi/mayavi/mayavi/mlab.py in <module>()
     25 
     26 # Mayavi imports
---> 27 from mayavi.tools.camera import view, roll, yaw, pitch, move
     28 from mayavi.tools.figure import figure, clf, gcf, savefig, \
     29     draw, sync_camera, close, screenshot

~/temporary/mayavi/mayavi/mayavi/tools/camera.py in <module>()
     22 # We can't use gcf, as it creates a circular import in camera management
     23 # routines.
---> 24 from .engine_manager import get_engine
     25 
     26 

~/temporary/mayavi/mayavi/mayavi/tools/engine_manager.py in <module>()
     12 from mayavi.preferences.api import preference_manager
     13 from mayavi.core.registry import registry
---> 14 from mayavi.core.engine import Engine
     15 from mayavi.core.off_screen_engine import OffScreenEngine
     16 from mayavi.core.null_engine import NullEngine

~/temporary/mayavi/mayavi/mayavi/core/engine.py in <module>()
     26 # Local imports.
     27 from tvtk.common import is_old_pipeline
---> 28 from mayavi.core.base import Base
     29 from mayavi.core.scene import Scene
     30 from mayavi.core.common import error, process_ui_events

~/temporary/mayavi/mayavi/mayavi/core/base.py in <module>()
     17     HasTraits, WeakRef, on_trait_change)
     18 from traitsui.api import TreeNodeObject
---> 19 from tvtk.pyface.tvtk_scene import TVTKScene
     20 from apptools.persistence import state_pickler
     21 from pyface.resource.api import resource_path

~/temporary/mayavi/mayavi/tvtk/pyface/tvtk_scene.py in <module>()
     26      Property, Instance, Event, Range, Bool, Trait, Str
     27 
---> 28 from tvtk.pyface import light_manager
     29 
     30 

~/temporary/mayavi/mayavi/tvtk/pyface/light_manager.py in <module>()
    128 # `CameraLight` class.
    129 ######################################################################
--> 130 class CameraLight(HasTraits):
    131 
    132     """This class manages a tvtk.Light object and a LightGlyph object."""

~/temporary/mayavi/mayavi/tvtk/pyface/light_manager.py in CameraLight()
    144     activate = Trait(False, false,
    145                      desc="specifies if the light is enabled or not")
--> 146     source = Instance(tvtk.Light, ())
    147 
    148     # FIXME: Traits Delegation does not work correctly and changes to

~/temporary/mayavi/mayavi/tvtk/tvtk_classes.zip/tvtk_classes/tvtk_helper.pyc in <lambda>(self)

~/temporary/mayavi/mayavi/tvtk/tvtk_classes.zip/tvtk_classes/tvtk_helper.pyc in get_class(name)

~/temporary/mayavi/mayavi/tvtk/tvtk_classes.zip/tvtk_classes/tvtk_helper.pyc in get_module(fname)

~/temporary/mayavi/mayavi/tvtk/tvtk_classes.zip/tvtk_classes/light.pyc in <module>()

~/temporary/mayavi/mayavi/tvtk/array_handler.py in <module>()
     26 
     27 # Enthought library imports.
---> 28 from tvtk.array_ext import set_id_type_array
     29 from tvtk.common import is_old_pipeline
     30 

ModuleNotFoundError: No module named 'tvtk.array_ext'
```
## 2)
Strangely enough, if, on the command line of that Python 3.6 environment I start spyder and import  `from mayavi import mlab` there are no errors.
However If, from spyder's IPython console I run the standard test figure  from [http://docs.enthought.com/mayavi/mayavi/mlab.html#a-demo](http://docs.enthought.com/mayavi/mayavi/mlab.html#a-demo) strangely _translucent_

## 3)
If I try to resort to an IPython console of a lower version of Python, i.e. a Python 3.5 environment - where mayavi was functional before this install, using qt4 - and invoke mayavi's [http://docs.enthought.com/mayavi/mayavi/mlab.html#a-demo](http://docs.enthought.com/mayavi/mayavi/mlab.html#a-demo) I now get the same error msgs as under 1) and in addition a message
```
********************************************************************************
WARNING: Imported VTK version (7.1) does not match the one used
         to build the TVTK classes (8.1). This may cause problems.
         Please rebuild TVTK.
********************************************************************************
```
Why (??) do two distinct Anaconda environments know about each other packages?
I thought the point about the environment stuff was to have independent  installs?
It seems that trying to install within the 3.6 env has broken the 3.5 env ...

More help, on how to get out of this would be very much appreciated,
Xaver

**Comment by xaverm** [comment] 2018-04-09 15:35
Hi, I'd like to add something to my previous post.

Regarding point **1)**: setting `export ETS_TOOLKIT=qt4, export QT_API=pyqt5` I can actually get rid of the error messages within the Python 3.6 env, when trying to use mayavi within a plain IPhyton console. So maybe(?) that was one of the culprits.

**However**, running http://docs.enthought.com/mayavi/mayavi/mlab.html#a-demo, the output looks broken
![mlabtest](https://user-images.githubusercontent.com/2843926/38506790-21a51b5a-3c1b-11e8-88db-e404d57a1f34.png)
Actually, the 'fire-flies' on the object are for real on my screen and rotating the object one realizes, that it seems partially transparent - which it has never been on my previous versions of Mayavi and Qt.

Xaver

**Comment by xaverm** [comment] 2018-04-10 15:42
@prabhuramachandran: Thank you. Now I got it.

From that my current answer to "Does Mayavi support PyQt5?" is: for me ... **not really**.
I've set up two running Anaconda envs.
### 1)
One with Python 3.5 and Qt4 and
```
mayavi                    4.5.0                    py35_3    conda-forge
pyface                    5.1.0                    py35_1    conda-forge
traitsui                  5.1.0                    py35_0    conda-forge
```
### 2)
One with Python 3.6 and Qt5 and
```
mayavi                    4.5.1.dev0                <pip>
pyface                    5.2.0.dev347              <pip>
traitsui                  5.2.0.dev420              <pip>
```
The latter pip installs have been made using Github's master repos.

Next, and for testing are two screen shots from running [http://docs.enthought.com/mayavi/mayavi/mlab.html#a-demo](http://docs.enthought.com/mayavi/mayavi/mlab.html#a-demo) in both envs. **As is obvious, drawing the scene in the Qt5 case happens without error msgs in priciple, however, the object is not plotted correctly, exhibiting a strange quasi-translucency and lots of fire-flies**

Would be really great, if this could be fixed!

### 1)
![mayavi qt4 python3 5](https://user-images.githubusercontent.com/2843926/38566459-00d23146-3ce4-11e8-83d2-c8a48ea6bba3.png)
### 2)
![mayavi qt5 python3 6](https://user-images.githubusercontent.com/2843926/38566508-1e4b42f8-3ce4-11e8-940a-cb3e13078cee.png)

**Comment by prabhuramachandran** [comment] 2018-04-10 16:46
What VTK version you are using?  I have no idea about the conda/conda-forge builds but there are VTK 8.1.0 wheels in pypi.  Can you try by pip installing VTK and see what happens?

**Comment by xaverm** [comment] 2018-04-10 17:53
> What VTK version you are using?

This is the one I had on the system when taking the preceding screenshots.
```
(py36) ~>conda list | grep vtk
vtk                       8.1.0                  py36_202    conda-forge
```
> Can you try by pip installing VTK and see what happens?

Yes, from [https://pypi.python.org/pypi/vtk](https://pypi.python.org/pypi/vtk). Now I have:
```
(py36) ~>conda list | grep vtk
vtk                       8.1.0                     <pip>
```
However ... no change as to the Mayavi scene output ... it looks exactly as in the previous Qt5 screenshot.

**Comment by prabhuramachandran** [comment] 2018-04-10 18:09
Possibly an OpenGL or hardware issue in that case.  I am running this all the time on a few machines without an issue.  What PyQt5 version?  Basically, none of this is really a mayavi or traits/pyface issue per-se as we are essentially sitting on top of VTK (which uses OpenGL) and Qt-whatever-version.  You could try downgrading to a conda-forge/conda version of VTK 7.x and see if that changes anything.  Sorry I am unable to be of any more help.  On your py35 env, which version of VTK and Qt are you using?  Try with those.

**Comment by xaverm** [comment] 2018-04-11 06:12
> Possibly an OpenGL or hardware issue in that case. 

Hmm. Would be interesting to know what kind of hardware issue that could be on a machine that runs several graphics intensive apps without such artifacts on a daily basis (including blender, mipav, mathematica, and paraview) and all of them out of a Qt5 driven desktop environment. And also, why would this hardware issue show up in the Qt5 version of mayavi and not in the Qt4 one?
So I keep my fingers crossed that the Qt4 version will be kept alive for some more time to come.

Anyway, thanks so much for your help up to this point!

**Comment by prabhuramachandran** [comment] 2018-04-11 07:04
Feel free to debug.  Mayavi is just using VTK and the QVTKRenderWindowInteractor, you could run a few simple VTK examples to check if the issue is with the VTK build, or if it is an issue with the Qt VTK interface, or an issue with Qt5.  Also note, different PyQt5 seems to have issues, for example on Windows using the latest Qt5 seems to fail completely and we have needed to downgrade to version 5.9.2...

**Comment by larsoner** [comment] 2018-05-02 19:43
This might depend on PyQt5 version, too. For me on macOS 5.9.2 gives a black screen (no errors) but on 5.10.2 it works just fine.

**Comment by prabhuramachandran** [comment] 2018-08-26 21:13
Closing as this is old and the situation has significantly improved now it seems.

**Closed by prabhuramachandran** 2018-08-26 21:13 UTC
