### ISSUE TITLE
'2dcircle' glyph and resolution

### ISSUE THREAD

**Issue by Franciturci** [enthought/mayavi#158] opened 2015-01-16 13:24 UTC
Hello,
I have tried to use the '2dcircle' mode for the points3d function both on the latest version of Mayavi available on Mac (via Homebrew) and on Ubuntu (apt-get). I have tried to get more sides than the default 8 using the keyword "resolution" but it seems to have no effect. For spheres, the keyword works as documented.

Is this a bug for the linear glyphs? Thanks.

**Comment by stefanoborini** [comment] 2016-04-27 15:45
Cannot reproduce in latest mayavi and vtk 6.3. This code works as expected

```
import numpy                                                                              
from mayavi.mlab import *                                                                 
                                                                                          
t = numpy.linspace(0, 4 * numpy.pi, 20)                                                   
cos = numpy.cos                                                                           
sin = numpy.sin                                                                           
                                                                                          
x = sin(2 * t)                                                                            
y = cos(t)                                                                                
z = cos(2 * t)                                                                            
s = 2 + sin(t)                                                                            
                                                                                          
points3d(x, y, z, s, colormap="copper", scale_factor=.25, mode='2dcircle', resolution=4)  
                                                                                          
show()
```

outputs squares. incrementing the resolution parameter to higher values produces circles of higher resolution.

Closing

**Closed by stefanoborini** 2016-04-27 15:45 UTC
