### ISSUE TITLE
set mask_points parameter will cause program crash

### ISSUE THREAD

**Issue by zhangruoyu** [enthought/mayavi#83] opened 2013-09-13 01:55 UTC
Run the following code

```python
from mayavi import mlab
import numpy as np
x, y, z = np.mgrid[0:1:20j, 0:1:20j, 0:1:20j]

u = np.sin(np.pi*x) * np.cos(np.pi*z)
v = -2*np.sin(np.pi*y) * np.cos(2*np.pi*z)
w = np.cos(np.pi*x)*np.sin(np.pi*z) + np.cos(np.pi*y)*np.sin(2*np.pi*z)

src = mlab.pipeline.vector_field(u, v, w)
vec = mlab.pipeline.vectors(src, mask_points=20, scale_factor=3.)
mlab.show()
```
a vtk error of Unable to allocate 2147483645 elements raise, and the program crashed.

I'am using windows 7, python 2.7, mayavi 4.3.0, vtk 5.10.1. I debug this and found that I can fix this problem with following code:

```python
from mayavi import mlab
import numpy as np
x, y, z = np.mgrid[0:1:20j, 0:1:20j, 0:1:20j]

u = np.sin(np.pi*x) * np.cos(np.pi*z)
v = -2*np.sin(np.pi*y) * np.cos(2*np.pi*z)
w = np.cos(np.pi*x)*np.sin(np.pi*z) + np.cos(np.pi*y)*np.sin(2*np.pi*z)

src = mlab.pipeline.vector_field(u, v, w)
vec = mlab.pipeline.vectors(src, scale_factor=3.)

mask = vec.glyph.mask_points
mask.maximum_number_of_points = 10000 
mask.on_ratio = 20
vec.glyph.mask_input_points = True

mlab.show()
```
The point is the default value of mask.maximum_number_of_points is 2147483645, I don't why vtk try to create an array of this size.

**Comment by st-j** [comment] 2015-01-23 11:10
I am seeing this, too:
* OS: OSX 10.10.1 (Yosemite)
* Enthought Canopy 1.5.1.2730 (tried both the 32 and 64 bit versions of Canopy, same result)
* Mayavi 4.3.1-2 installed via Canopy package manager

The following code (taken from the Mayavi docs) crashes:

    import numpy as np
    from mayavi import mlab
    
    x, y, z = np.mgrid[0:1:20j, 0:1:20j, 0:1:20j]
    
    u =    np.sin(np.pi*x) * np.cos(np.pi*z)
    v = -2*np.sin(np.pi*y) * np.cos(2*np.pi*z)
    w = np.cos(np.pi*x)*np.sin(np.pi*z) + np.cos(np.pi*y)*np.sin(2*np.pi*z)
    
    src = mlab.pipeline.vector_field(u, v, w)
    mlab.pipeline.vectors(src, scale_factor=1., mask_points=2)

The error message is as follows:

    ERROR: In /Users/vagrant/pisi-64bit/tmp/VTK-5.10.12/work/VTK5.10.1/Common/vtkDataArrayTemplate.txx, line 144
    vtkFloatArray (0x1214f3390): Unable to allocate 9223372036854775805 elements of size 4 bytes. 
    
    libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

After removing the `mask_points` in the last line (i.e., after changing the last line to `mlab.pipeline.vectors(src, scale_factor=1.)` the code works as expected.

Any more information I could provide?

**Comment by st-j** [comment] 2015-01-23 11:26
By the way:
* 9223372036854775805 times 4 is *exactly* 2^65
* 2147483645 times 4 is very close to 2^33 (@zhangruoyu: are you sure you didn't mistype the number?  In fact, 2147483648 times 4 is 2^33)

The error I pasted above was from the 64-bit OSX version, and while I don't have it installed anymore, I'm almost sure the number in my crash with the 32-bit version was something starting with 21...). I assume zhangruoyu's Window's version was 32 bit.

Probably some underflow error happening here?

P.S.: 2^65 bytes are 32 Exabytes (32 exbibytes, to be correct). If this bugs gets my employer to buy me a Exabyte memory upgrade for my notebook, please leave it in ;)

**Comment by jtceleron** [comment] 2015-03-18 18:18
I am also having this issue. Is there any solution for this?
My OS is OSX 10.10.2.
Canopy 1.5.2 64 bit.

**Comment by stefanoborini** [comment] 2016-04-04 15:13
tested on OSX 10.10.3, mayavi 4.4.4, VTK 6.2.0. Seems to be a bug in VTK 5. @st-j can you please confirm that the problem is no longer there if you upgrade VTK?

**Comment by st-j** [comment] 2016-04-05 09:00
Yes, the bug is gone now: Mayavi 4.4.3 and VTK 6.3 (again both from Enthought python), on OSX 10.10.5

**Comment by stefanoborini** [comment] 2016-04-05 09:11
Closing then. Thank you @st-j

**Closed by stefanoborini** 2016-04-05 09:11 UTC
