### ISSUE TITLE
Speed up point cloud visualization process

### ISSUE THREAD

**Issue by mvish7** [enthought/mayavi#1013] opened 2021-02-23 17:55 UTC
Hi,

I'm using mayavi to visualize the LiDAR point cloud. In my case, a single-point cloud has around 100,000 to 150,000 points.
I colorize each point in a point cloud while visualizing it. I use the following code for it.

```
# creating scalar_scatter of points
pt_src = mlab.pipeline.scalar_scatter(points[:, 0], points[:, 1], points[:, 2], figure=fig)

# create point wise colormap 
rgba = custom_colormap(labels)
rgba[:, -1] = 255

# adding created color map
pt_src.add_attribute(rgba, 'colors')
pt_src.data.point_data.set_active_scalars('colors')

# adding the created points to pipeline and setting the scale value
scatter_pipeline = mlab.pipeline.glyph(pt_src)
scatter_pipeline.glyph.glyph.scale_factor = 0.08
scatter_pipeline.glyph.scale_mode = 'data_scaling_off'

mlab.view(
    azimuth=180,
    elevation=75,
    focalpoint=[4.0, -1.0, -2.0],
    distance=90.0,
    figure=fig
)
```  

My Problem:
This code takes around 5-6 seconds to visualize and save one point cloud. As I have more than 25, 000 point clouds to visualize I would like to speed up this process. Hence,

1. Could you please advise if the method I'm using is the fastest method of visualizing the colorized point clouds??
2. Is there an alternative method that is faster and can also visualize colorized point clouds??
3. Are there any other tips to speed up the current method?

Edit:
I have a workstation with CPU>11GB RAM and 2080ti GPU onboard.
I'm using` mayavi 4.7, VTK 8.2, QT 5.2`

**Comment by prabhuramachandran** [comment] 2021-02-27 12:20
This is not really an issue so I am closing this but to answer your question, the problem is that by default the glyphs will use spheres, so if you use the defaults, it will generate O(64) triangles per point in your dataset, so with just 100k points you have 6 million triangles which will not very quick.  Instead try the following:
```
import numpy as np
x, y, z = np.random.random((3, 100000))
from mayavi import mlab
g = mlab.points3d(x, y, z, z, mode='point')
g.actor.property.render_points_as_spheres =  True
g.actor.property.point_size = 20
```
Try it and see, it is *much* faster.

**Closed by prabhuramachandran** 2021-02-27 12:20 UTC
