### ISSUE TITLE
problem building mayavi

### ISSUE THREAD

**Issue by RobbieScott** [enthought/mayavi#273] opened 2016-01-08 11:52 UTC
I'm trying to do the following:
pip install mayavi
i have, I believe, installed all of the dependencies, and vtk imports into python ok. However I get the following error. I have no real idea what is going wrong. Can anyone help?

Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/k6/c1091t595v118h7xjv_tcv400000gn/T/pip-build-rhfqxf/mayavi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/k6/c1091t595v118h7xjv_tcv400000gn/T/pip-D2AlUq-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    ----------------------------------------------------------------------
    Building TVTK classes...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/k6/c1091t595v118h7xjv_tcv400000gn/T/pip-build-rhfqxf/mayavi/setup.py", line 471, in <module>
        **config
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/command/install.py", line 59, in run
        r = self.setuptools_run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/command/install.py", line 33, in setuptools_run
        return old_install_mod._install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/k6/c1091t595v118h7xjv_tcv400000gn/T/pip-build-rhfqxf/mayavi/setup.py", line 303, in run
        build_tvtk_classes_zip()
      File "/private/var/folders/k6/c1091t595v118h7xjv_tcv400000gn/T/pip-build-rhfqxf/mayavi/setup.py", line 290, in build_tvtk_classes_zip
        gen_tvtk_classes_zip()
      File "tvtk/setup.py", line 61, in gen_tvtk_classes_zip
        gen = TVTKGenerator('')
      File "tvtk/code_gen.py", line 57, in __init__
        self.wrap_gen = WrapperGenerator()
      File "tvtk/wrapper_gen.py", line 44, in __init__
        self.parser = vtk_parser.VTKMethodParser()
      File "tvtk/vtk_parser.py", line 111, in __init__
        self._tree.create()
      File "tvtk/class_tree.py", line 255, in create
        self._generate_hierarchy(klass)
      File "tvtk/class_tree.py", line 149, in _generate_hierarchy
        node = self.get_node(klass.__name__, create=1)
      File "tvtk/class_tree.py", line 203, in get_node
        return self.add_node(self.get_class(name))
      File "tvtk/class_tree.py", line 168, in get_class
        raise KeyError, "Cannot find class of name %s"%name
    KeyError: 'Cannot find class of name vtkDenseArray_I10vtkVariantE'

**Comment by z--m-n** [comment] 2016-01-26 11:20
I had a similar problem yesterday. After a homebrew update of python from 2.7.10_2 to 2.7.11 a number of python modules stopped working, including mayavi. It may be that mayavi/vtk dependencies were set up correctly before and not yet for python 2.7.11 on my system. I could get mayavi 4.4.3 to reinstall, but I had to ...

... revert to python 2.7.10_2 (`brew switch python 2.7.10_2`),
make vtk5 available (`brew link --force vtk5`), 
then mayavi 4.4.3 could be upgraded as usual (`pip install --upgrade mayavi`) within a virtualenv python.

Perhaps someone can post the magic short list of homebrew commands needed to fix dependencies after a python upgrade?

**Comment by jenshnielsen** [comment] 2016-01-26 11:24
@z--m-n  That sounds like a duplicate of https://github.com/Homebrew/homebrew-science/issues/3162 
I guess the revision of VTK(5) needs to be bumped in Homebrew science. 

The other work around is to rebuild vtk from source

```
brew reinstall vtk5 --build-from-source 
```

The master branch should support VTK 6.3 but I think you need an older version of VTK for 4.4.3
so it makes sense that you have to install vtk5

**Comment by z--m-n** [comment] 2016-01-26 14:03
@jenshnielsen Very helpful link.

I did spend some time to get all dependencies satisfied for mayavi and vtk (using homebrew and virtualenv) on OSX for mavericks. I am sure things are better now. Thanks!

**Comment by stefanoborini** [comment] 2016-04-26 13:34
From what I read, seems unrelated to mayavi. Closing

**Closed by stefanoborini** 2016-04-26 13:34 UTC
