### ISSUE TITLE
Unable to create .png or any other image format. However, .pdf works.

### ISSUE THREAD

**Issue by Kekushke** [enthought/mayavi#629] opened 2018-04-18 10:47 UTC
Tried many different versions of VTK (8.x and 6.x) libraries along with `mayavi2` `Version 4.5.0`, but unable to save `.png ` or any other image formats. However, `.pdf ` worked. This is with `Python 2.7.x ` and `Ubuntu 16.04` with all the latest updates. Could this be issue with upstream VTK libraries?

**Comment by Kekushke** [comment] 2018-05-02 19:07
.png still doesn't work. For .pdf should also add that although .pdf is created, it opens a pop-up before the .pdf is created asking for options related to pdf creation setup, and thus blocking further execution until pop-up is confirmed.

**Comment by prabhuramachandran** [comment] 2018-05-02 19:26
That is rather strange.  What exact code are you using for this?
```
from mayavi import mlab
mlab.test_plot3d()
mlab.savefig('/tmp/t.png')
```
Works perfectly well for me but on a Mac, I can test on Linux later but I think it does work pretty well there also.  How did you install Mayavi?  Is this from github master?  Version 4.5.0 is a bit old.  I'd recommend the latest version from github.  As regards PDFs you can do this::
```
from tvtk.api import tvtk
e = tvtk.GL2PSExporter()
mlab.savefig('/tmp/t.pdf', exp=e)
```

**Comment by Kekushke** [comment] 2018-05-03 01:29
The environment is `conda`, with ` python 2.7`. I am using `mayavi 4.5.0` installed from conda. Currently `vtk` installed via `conda`  is at 8.1.0.   The error is now different (related to magnification, which I think is fixed already reading the history). So, as you suggested, I am going to try new version from github of Mayavi and try again. Let me report you back shortly. Just wanted to ask will `python 2.7` be Okay... or we must switch to `python 3.5`?

**Comment by prabhuramachandran** [comment] 2018-05-03 03:32
Yes, 2.7 should be just fine.

**Comment by Kekushke** [comment] 2018-05-03 03:41
Prof. @prabhuramachandran , as you suggested, setup, build and installed  `mayavi (4.5.1.dev0)` directly from git. Able to see the test plot in a window from the script you posted. Had to add `mplab.show()` to stop X-error. Creating '.png' still not possible. Creates blank black square. I have the following. The environment is conda, with python 2.7. I am on` ubuntu 16.04`  Cleaned up everything, and installed the followings via `pip`.

```
vtk (8.1.0)
pyface (6.0.0)
traits (4.6.0)
traitsui (6.0.0)
```

May be I am still missing something. Any ideas?

BTW, `nosetests` on `mayavi` git dev version gives following error multiple times:

`ERROR: Failure: ImportError (No module named array_ext)
`

**Comment by prabhuramachandran** [comment] 2018-05-03 03:44
I suspect you are in the same directory as the git clone (mayavi) so it is trying to do a local import.  cd out of that directory and try.  Yes, you do need to `mlab.show` or use IPython with a suitable GUI as is documented here (http://docs.enthought.com/mayavi/mayavi/mlab.html).

**Comment by prabhuramachandran** [comment] 2018-05-03 03:45
Not sure about your blank window though, that sounds very weird.  What version of PyQt?

**Comment by Kekushke** [comment] 2018-05-03 09:47
With the above setup; found something interesting. If I have `mlab.options.offscreen = True` in the `python` program, such as below:

```
from mayavi import mlab
mlab.options.offscreen = False
mlab.test_plot3d()
mlab.savefig('t.png')
mlab.show()
```

Then it creates `.png`  correctly. However, if `offscreen` related option is set to `False` or if the line is removed, then `.png` is dark box again!

**Comment by prabhuramachandran** [comment] 2018-05-21 10:09
@Kekushke -- I am not able to reproduce this on a few linux machines.  I tried with a couple of machines running Ubuntu 16.04 using vtk 8.1.0 and Mayavi from github and saving the scene works.  :(

**Comment by prabhuramachandran** [comment] 2018-05-21 13:04
One possible explanation is that for some reason on your hardware, the frontbuffer of the render window is blank and the valid image is only in the backbuffer.  This is perhaps why the offscreen option works for you.  So in your case you could try this code to save:
```
from mayavi import mlab
s = mlab.test_plot3d()
s.scene.off_screen_rendering = True
mlab.savefig('/tmp/t.png')
s.scene.off_screen_rendering = False
```
For now I am closing this as I think you may have a workaround and I am unable to reproduce this.  Please reopen or comment on this if you have further issues or information.  Thanks for your patience.

**Closed by prabhuramachandran** 2018-05-21 13:04 UTC
