### ISSUE TITLE
Importing mlab results in Glib errors

### ISSUE THREAD

**Issue by MichaelClerx** [enthought/mayavi#305] opened 2016-03-02 00:44 UTC
Hi all,

When trying to import mayavi's mlab (from mayavi import mlab), I get a bunch of Glib errors:

```
(pca.py:26970): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'
(pca.py:26970): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(pca.py:26970): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
(pca.py:26970): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(pca.py:26970): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(pca.py:26970): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(pca.py:26970): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(pca.py:26970): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplay'
(pca.py:26970): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(pca.py:26970): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed
(pca.py:26970): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(pca.py:26970): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```

Mayavi's worked fine for me in the past, but I don't use it frequently so it's hard to tell what changes I've made to my system since it last worked. One major thing is upgrading to Fedora 23.

Does anybody have any ideas where I can look to fix this issue?

**Comment by stefanoborini** [comment] 2016-04-28 11:45
I guess that dependency libraries have been upgraded and it compromises your mayavi installation.
I am closing this because it's hard to reproduce, but I suggest you try again with a fresh installation of mayavi and check if you still get the errors.

**Closed by stefanoborini** 2016-04-28 11:45 UTC
