### ISSUE TITLE
mlab.pipeline.volume(scalars) fails randomly

### ISSUE THREAD

**Issue by thomasaarholt** [enthought/mayavi#468] opened 2016-12-12 20:48 UTC
The code below ran in one instance, and then failed in the next after plotting a separate set of data. The data are 50x50x50 numpy arrays with intensities between 0 and 64 in float. This is in the jupyter notebook on latest Mac and latest traits. Advice is greatly appreciated. 

```python
vol = np.array(some_data)
scalars = mlab.pipeline.scalar_field(vol)
mlab.pipeline.volume(scalars)
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
<ipython-input-73-d1f5eb6d8180> in <module>()
----> 1 mlab.pipeline.volume(scalars)

/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/mayavi/tools/pipe_base.py in the_function(*args, **kwargs)
     36 def make_function(factory_class):
     37     def the_function(*args, **kwargs):
---> 38         factory = factory_class(*args, **kwargs)
     39         return factory._target
     40 

/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/mayavi/tools/pipe_base.py in __init__(self, parent, **kwargs)
    144             self._do_redraw = not scene.disable_render
    145             scene.disable_render = True
--> 146         if issubclass(self._target.__class__, Filter):
    147             self._engine.add_filter(self._target, obj=parent)
    148         else:

/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/traits/trait_types.py in create_default_value(self, *args, **kw)
   2935                 raise TraitError('Unable to locate class: ' + args[0])
   2936 
-> 2937         return klass( *args[1:], **kw )
   2938 
   2939     #: fixme: Do we still need this method using the new style?...

/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/mayavi/core/module.py in __init__(self, **traits)
     56 
     57         # Let the module setup its pipeline.
---> 58         self.setup_pipeline()
     59 
     60     def __get_pure_state__(self):

/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/mayavi/modules/volume.py in setup_pipeline(self)
    316         vp.on_trait_change(self.render)
    317 
--> 318         available_mappers = find_volume_mappers()
    319         if is_volume_pro_available():
    320             self._mapper_types.append('VolumeProMapper')

/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/mayavi/modules/volume.py in find_volume_mappers()
     51             try:
     52                 klass = getattr(tvtk, name)
---> 53                 inst = klass()
     54             except TypeError:
     55                 pass

/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/tvtk/tvtk_classes.zip/tvtk_classes/smart_volume_mapper.pyc in __init__(self, obj, update, **traits)

/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/tvtk/tvtk_base.py in __init__(self, klass, obj, update, **traits)
    339         # Update the traits based on the values of the VTK object.
    340         if update:
--> 341             self.update_traits()
    342 
    343         # Setup observers for the modified event.

/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/tvtk/tvtk_base.py in update_traits(self, obj, event)
    494             else:
    495                 try:
--> 496                     setattr(self, name, val)
    497                 except traits.TraitError:
    498                     if name in self._allow_update_failure_:

/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/traits/trait_types.py in validate(self, object, name, value)
   1763         """ Validate that the value is in the specified range.
   1764         """
-> 1765         return getattr( self, self._validate )( object, name, value )
   1766 
   1767     def float_validate ( self, object, name, value ):

/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/traits/trait_types.py in long_validate(self, object, name, value)
   1816             pass
   1817 
-> 1818         self.error( object, name, value )
   1819 
   1820     def _get_default_value ( self, object ):

/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/traits/trait_handlers.py in error(self, object, name, value)
    171         """
    172         raise TraitError( object, name, self.full_info( object, name, value ),
--> 173                           value )
    174 
    175     def full_info ( self, object, name, value ):

TraitError: The 'vector_component' trait of a SmartVolumeMapper instance must be 0 <= a long integer <= 3, but a value of 44544 <class 'int'> was specified.
```

**Comment by thomasaarholt** [comment] 2016-12-12 20:52
The bug is reproducable with the following code:
```python
from mayavi import mlab
import numpy as np

x, y, z = np.ogrid[-10:10:20j, -10:10:20j, -10:10:20j]
s = np.sin(x*y*z)/(x*y*z)
scalars = mlab.pipeline.scalar_field(s)

mlab.pipeline.volume(scalars, transparency=True)
```

**Comment by scholi** [comment] 2017-05-02 20:32
Does someone has a workaround yet?

**Comment by prabhuramachandran** [comment] 2017-08-08 12:31
Well, it works for me on master.  The transparency argument is not valid IIRC.  So,
```
from mayavi import mlab
import numpy as np

x, y, z = np.ogrid[-10:10:20j, -10:10:20j, -10:10:20j]
s = np.sin(x*y*z)/(x*y*z)
scalars = mlab.pipeline.scalar_field(s)

mlab.pipeline.volume(scalars)
```
works on master.  I am closing this for now, if the issue is still not fixed, please reopen.

**Closed by prabhuramachandran** 2017-08-08 12:31 UTC

**Comment by fkjogu** [comment] 2017-08-23 09:20
After installing mayavi with
```
pip3 install --user -U git+https://github.com/enthought/mayavi.git
```
I still run into this issue regularly. Also using the above code.
