### ISSUE TITLE
Wrong colors on Ubuntu default theme

### ISSUE THREAD

**Issue by Mystic-Mirage** [enthought/mayavi#17] opened 2011-10-01 23:27 UTC
On ubuntu mayavi2 looks too dark.

http://itmag.es/4GId4

**Comment by stefanoborini** [comment] 2016-04-04 10:00
The issue in traitsui has been closed as can't reproduce. I can't reproduce it either on ubuntu. Backend now must be qt due to wx incompatibilty. Closing.

**Closed by stefanoborini** 2016-04-04 10:00 UTC
