### ISSUE TITLE
text3d complaining when rendering to empty figure

### ISSUE THREAD

**Issue by patricksnape** [enthought/mayavi#82] opened 2013-08-27 18:32 UTC
Setup
---------
**OS:** Ubuntu 13.04
```
mayavi==4.3.0
pyface==4.3.0
traits==4.3.0
traitsui==4.3.0
vtk==5.8.0
```
I installed ``vtk`` via ``apt-get`` and ``mayavi`` via ``pip``.

Replicate bug
--------------------
  - Open IPython (1.0.0): ``ipython --gui=wx``
  - Run following:

```
from mayavi import mlab
mlab.text3d(0, 0, 0, 'label')
```

  - Popup opens saying: ``No data: cannot use a Filter/Module/ModuleManager``
  - IPython prints: ``No handlers could be found for logger "mayavi.core.common"``

Strange workaround
-----------------------------
For some reason, running the following seems to work OK.

```
from mayavi import mlab
mlab.points3d(0, 0, 0)
mlab.text3d(0, 0, 0, 'label')
```

However, the empty figure doesn't seem to have anything to do with it because running the following replicates the bug behaviour:

```
from mayavi import mlab
fig = mlab.figure()
mlab.text3d(0, 0, 0, 'label', figure=fig)
```

**Comment by stefanoborini** [comment] 2016-04-04 15:03
Not a bug in my opinion, it's expected behavior. Closing.

**Closed by stefanoborini** 2016-04-04 15:03 UTC

**Comment by steffen-sch** [comment] 2020-04-24 15:34
From a perspective of an inexperienced user, this behaviour is very hard to understand. 
It produces frustration.
I tried to draw two texts. I used the same code line. 
Surprise: One was drawn - one not.
This bug has taken me at least 10 minutes to find.
This issue was the only way to find the cause for me.
