### ISSUE TITLE
Stuck at `Building wheel for mayavi (setup.py)`

### ISSUE THREAD

**Issue by woochangchung** [enthought/mayavi#1065] opened 2021-08-05 21:38 UTC
Here is my installation environment: Ubuntu 20.04 LTS on a ThinkPad P15 laptop
![image](https://user-images.githubusercontent.com/26212312/128424515-4374d0be-34f6-4d4f-99ce-98a3e7d1d582.png)
And when I do `pip install mayavi`, I get stuck during the `Building wheel` process:
![image](https://user-images.githubusercontent.com/26212312/128424347-f6f89a15-0749-4afe-af27-fd0cbe5ef63e.png)

Python version is 3.8.10.

**Comment by TravisPetit** [comment] 2021-08-06 06:55
Same problem here, also on Ubuntu 20.04 LTS.
And when I try to install the [bleeding edge version](https://github.com/enthought/mayavi#bleeding-edge) by cloning the repository I get a TVTK - VTK incompatibility error, as pointed out here  #1061.

**Comment by DanMunchie** [comment] 2021-08-06 14:35
Same issue on Windows 10 64bit

**Comment by Sbozzolo** [comment] 2021-08-09 18:17
[Here](https://github.com/Sbozzolo/kuibit/actions/runs/1086276816) is another (reproducible) example where it is not possible to build `mayavi` on Ubuntu 20.04 on a GitHub Actions runner.

**Comment by Kukuster** [comment] 2021-08-15 13:15
reinstalling dependencies did help me with this. Try removing and installing:

• vtk
• pyqt5
• libvtk6-dev
• libpq5

again. Then try to install mayavi again

**Comment by fbottarel** [comment] 2021-08-18 15:57
On Ubuntu 18.04 I managed to un-stuck the mayavi setup with the configuration

- `vtk6`, `libvtk6-dev` and `libvtk6-dev-qt`  installed via `apt` 
- `PyQt5` and `vtk==8.1.0` installed via `pip3`
- Python 3.6.9

Not sure it will help tho.  @woochangchung try downgrading the vtk package version installed via pip3 to something < 9.0.3

**Comment by carlsonmark** [comment] 2021-08-25 00:31
Downgrading to vtk==9.0.1 worked for me on Ubuntu 20.04

**Comment by StephanSneijders** [comment] 2021-09-03 09:31
vtk 9.0.1 with latest version of wheel works for me
vtk 9.0.3 with wheel 0.34.2 works for me
vtk 9.0.3 with latest version of wheel doesn't work for me

I don't know what the true issue is here, but now I just used the wheel 0.34.2 option.

**Comment by SiddharthaMithiya** [comment] 2021-11-08 19:23
Experiencing same thing, vtk-9.0.1 not available for python 3.9 starting from 9.0.2.
A specific solution in needed, where everyone facing same problem in installation.

**Comment by rahulporuri** [comment] 2021-11-09 10:46
@fwilliams and @SiddharthaMithiya we're working on making a release which supports the latest vtk versions (9.0.3 and 9.1.0 now). The current development branch contains the necessary fixes for vtk 9.0.3 so if possible, we recommend that you install mayavi from github directly, until we make a release.

**Comment by SiddharthaMithiya** [comment] 2021-11-10 04:07
Thank you so much for your support.
*Actually let me explain the situation.*
We are doing our project work on Quantum mechanics this year, and we want
to use mayavi, for 3d analysis, cause it's better than matplotlib's 3d
environment.
And we all stuck with this situation of installation.

Now, can you please explain me how to install it from GitHub?
If we arange a *Google meet* then it will be very very helpful and fruitful
for us. If you are agree for a Google meet then I will be forever grateful
to you.
I beg you to help us.

Thanking you in advance.

**Comment by rahulporuri** [comment] 2021-11-10 04:43
> Now, can you please explain me how to install it from GitHub?

You need to do `pip install git+https://github.com/mayavi.git@master#egg=mayavi`. Ref https://pip.pypa.io/en/stable/topics/vcs-support/#git for more information regarding installing packages from git/github.

**Comment by SiddharthaMithiya** [comment] 2021-11-10 05:01
sir, i tried it but it is giving this error

ERROR: Could not find a version that satisfies the requirement mayavi
(unavailable) (from versions: 4.3.1, 4.4.1, 4.4.2, 4.4.3, 4.4.4, 4.5.0,
4.6.0, 4.6.1, 4.6.2, 4.7.0, 4.7.1, 4.7.2, 4.7.3)
ERROR: No matching distribution found for mayavi (unavailable)

**Comment by rahulporuri** [comment] 2021-11-10 06:35
@SiddharthaMithiya the command I mentioned earlier is wrong. Can you please run this command in your python environment - `python -m pip install vtk==9.0.3 git+https://github.com/enthought/mayavi.git@master#egg=mayavi` and copy-paste the full output of that command?

**Comment by SiddharthaMithiya** [comment] 2021-11-10 06:57
*I tried it sir.*
*But still it giving ERROR, while building wheel for mayavi.*
*Here is the error massage below.*

"
Building wheels for collected packages: mayavi
  Building wheel for mayavi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command:
'C:\Users\SIDDHARTHA\AppData\Local\Programs\Python\Python39\python.exe' -u
-c 'import io, os, sys, setuptools, tokenize; sys.argv[0] =
'"'"'C:\\Users\\SIDDHARTHA\\AppData\\Local\\Temp\\pip-install-l39rok_y\\mayavi_396f7023c28b4c458584db94aa1f5b85\\setup.py'"'"';
__file__='"'"'C:\\Users\\SIDDHARTHA\\AppData\\Local\\Temp\\pip-install-l39rok_y\\mayavi_396f7023c28b4c458584db94aa1f5b85\\setup.py'"'"';f
= getattr(tokenize, '"'"'open'"'"', open)(__file__) if
os.path.exists(__file__) else io.StringIO('"'"'from setuptools import
setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
bdist_wheel -d 'C:\Users\SIDDHARTHA\AppData\Local\Temp\pip-wheel-9gsaspcy'
       cwd:
C:\Users\SIDDHARTHA\AppData\Local\Temp\pip-install-l39rok_y\mayavi_396f7023c28b4c458584db94aa1f5b85\
  Complete output (45 lines):
  running bdist_wheel
  running build
  ----------------------------------------------------------------------
  Building TVTK classes... Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File
"C:\Users\SIDDHARTHA\AppData\Local\Temp\pip-install-l39rok_y\mayavi_396f7023c28b4c458584db94aa1f5b85\setup.py",
line 411, in <module>
      setup(
    File
"C:\Users\SIDDHARTHA\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\distutils\core.py",
line 169, in setup
      return old_setup(**new_attr)
    File
"C:\Users\SIDDHARTHA\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py",
line 165, in setup
      return distutils.core.setup(**attrs)
    File
"C:\Users\SIDDHARTHA\AppData\Local\Programs\Python\Python39\lib\distutils\core.py",
line 148, in setup
      dist.run_commands()
    File
"C:\Users\SIDDHARTHA\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py",
line 966, in run_commands
      self.run_command(cmd)
    File
"C:\Users\SIDDHARTHA\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py",
line 985, in run_command
      cmd_obj.run()
    File
"C:\Users\SIDDHARTHA\AppData\Local\Programs\Python\Python39\lib\site-packages\wheel\bdist_wheel.py",
line 299, in run
      self.run_command('build')
    File
"C:\Users\SIDDHARTHA\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py",
line 313, in run_command
      self.distribution.run_command(command)
    File
"C:\Users\SIDDHARTHA\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py",
line 985, in run_command
      cmd_obj.run()
    File
"C:\Users\SIDDHARTHA\AppData\Local\Temp\pip-install-l39rok_y\mayavi_396f7023c28b4c458584db94aa1f5b85\setup.py",
line 268, in run
      build_tvtk_classes_zip()
    File
"C:\Users\SIDDHARTHA\AppData\Local\Temp\pip-install-l39rok_y\mayavi_396f7023c28b4c458584db94aa1f5b85\setup.py",
line 254, in build_tvtk_classes_zip
      gen_tvtk_classes_zip()
    File "tvtk\setup.py", line 98, in gen_tvtk_classes_zip
      # as things get removed from the original list, the indices
    File
"C:\Users\SIDDHARTHA\AppData\Local\Temp\pip-install-l39rok_y\mayavi_396f7023c28b4c458584db94aa1f5b85\tvtk\code_gen.py",
line 132, in generate_code
      self._write_wrapper_class(node, tvtk_name)
    File
"C:\Users\SIDDHARTHA\AppData\Local\Temp\pip-install-l39rok_y\mayavi_396f7023c28b4c458584db94aa1f5b85\tvtk\code_gen.py",
line 224, in _write_wrapper_class
      self.wrap_gen.generate_code(node, out)
    File
"C:\Users\SIDDHARTHA\AppData\Local\Temp\pip-install-l39rok_y\mayavi_396f7023c28b4c458584db94aa1f5b85\tvtk\wrapper_gen.py",
line 242, in generate_code
      self._gen_methods(node, out)
    File
"C:\Users\SIDDHARTHA\AppData\Local\Temp\pip-install-l39rok_y\mayavi_396f7023c28b4c458584db94aa1f5b85\tvtk\wrapper_gen.py",
line 361, in _gen_methods
      get_set, allow_update_failure = self._gen_get_set_methods(klass, out)
    File
"C:\Users\SIDDHARTHA\AppData\Local\Temp\pip-install-l39rok_y\mayavi_396f7023c28b4c458584db94aa1f5b85\tvtk\wrapper_gen.py",
line 748, in _gen_get_set_methods
      if not meths[vtk_attr_name] and get_sig[0][1]:
  IndexError: list index out of range


  Failed on Logger
  (#3 of 11 nodes, #18 of 32 subnodes)

  ----------------------------------------
  ERROR: Failed building wheel for mayavi
"
*Sir, it is also to be mentioned that, after the error message, this thing
also happened.*
"
Running setup.py clean for mayavi
Failed to build mayavi
Installing collected packages: vtk, mayavi
  Attempting uninstall: vtk
    Found existing installation: vtk 9.1.0
    Uninstalling vtk-9.1.0:
      Successfully uninstalled vtk-9.1.0
    Running setup.py install for mayavi ... done
  DEPRECATION: mayavi was installed using the legacy 'setup.py install'
method, because a wheel could not be built for it. A possible replacement
is to fix the wheel build issue reported above. Discussion can be found at
https://github.com/pypa/pip/issues/8368
Successfully installed mayavi-4.7.4.dev0 vtk-9.0.3
"
*Sir, what should I do now?*

**Comment by rahulporuri** [comment] 2021-11-10 07:01
> Successfully installed mayavi-4.7.4.dev0 vtk-9.0.3

@SiddharthaMithiya ignoring the first error, the installation seems to have worked because of this message. I think the installation worked. Can you try running `import mayavi` from the python prompt?

**Comment by SiddharthaMithiya** [comment] 2021-11-10 07:15
yes sir it's working fine.
i'm following pravu Ramachandan's tutorial video in youtube lectured in
Scipy 2018.
i saved a test plot also.

**Comment by SiddharthaMithiya** [comment] 2021-11-10 07:43
It is working fine sir.
As I work mainly in pycharm, i did the same thing in pycharm terminal and i
can use it there also.
THANK YOU SO MUCH SIR.

**Comment by rahulporuri** [comment] 2021-11-15 10:39
closing as the latest 4.7.4 mayavi release fixes this issue. please try reinstalling mayavi.

**Closed by rahulporuri** 2021-11-15 10:39 UTC

**Comment by yumendecc** [comment] 2022-08-24 10:47
> 在 Ubuntu 20.04 上降级到 vtk==9.0.1 对我有用
对我也有用 ubuntu 20.04

**Comment by AmruthGudigar111** [comment] 2023-06-09 10:12
@rahulporuri 
I am getting error like this when i trying to install in windows 64 bit system Python version is 3.11
error: Command "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\mihit\AppData\Local\Temp\pip-build-env-_zvi10m9\overlay\Lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.11\numpy\distutils\include -ID:\anaconda\envs\mayavi\include -ID:\anaconda\envs\mayavi\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um /Tctvtk\src\array_ext.c /Fobuild\temp.win-amd64-cpython-311\Release\tvtk\src\array_ext.obj" failed with exit status 2
      INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : msvc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : none
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> C:\Users\mihit\AppData\Local\Temp\pip-install-p4o_c13a\mayavi_4162572215984310b2bcd11c08e91c8d\build\temp.win-amd64-cpython-311\Release\ccompiler_opt_cache_ext.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mayavi
Failed to build mayavi
ERROR: Could not build wheels for mayavi, which is required to install pyproject.toml-based projects

PLease help me with this error


![image](https://github.com/enthought/mayavi/assets/57893983/1c5df0c3-0ec0-47b9-9f3d-9590ca376fe5)
