### ISSUE TITLE
installation stops at running build

### ISSUE THREAD

**Issue by KitCarson03** [enthought/mayavi#1070] opened 2021-08-14 21:01 UTC
the installation via pip install mayavi stops at
running build
without giving error or interrupting, it just stay there

**Comment by Emanoel-sabidussi** [comment] 2021-08-16 11:49
Hi, this seems to be vtk related issue. Maybe compatibility issues with VTK 9.0+ (as mentioned in this thread: https://github.com/enthought/mayavi/issues/942, which should've been solved, but apparently it isn't).

I am having the same issue running Python3.8.
I tried to downgrade vtk to 8.1.2, but my venv is python3+ (I can't change that), and vtk only has versions 9.0+ available.

**Comment by Emanoel-sabidussi** [comment] 2021-08-16 11:50
Also, possible duplicate of: https://github.com/enthought/mayavi/issues/1065

**Comment by rahulporuri** [comment] 2021-11-15 10:38
closing as the latest 4.7.4 mayavi release fixes this issue. please try reinstalling mayavi.

**Closed by rahulporuri** 2021-11-15 10:38 UTC
