### ISSUE TITLE
Text the last letter gets cropped

### ISSUE THREAD

**Issue by joonro** [enthought/mayavi#81] opened 2013-08-22 20:02 UTC
For example, with the `surf()` example (http://docs.enthought.com/mayavi/mayavi/auto/mlab_helper_functions.html#mayavi.mlab.surf):

```python
import numpy
from mayavi.mlab import *

def test_triangular_mesh():
    """An example of a cone, ie a non-regular mesh defined by its
        triangles.
    """
    n = 8
    t = numpy.linspace(-numpy.pi, numpy.pi, n)
    z = numpy.exp(1j*t)
    x = z.real.copy()
    y = z.imag.copy()
    z = numpy.zeros_like(x)

    triangles = [(0, i, i+1) for i in range(1, n)]
    x = numpy.r_[0, x]
    y = numpy.r_[0, y]
    z = numpy.r_[1, z]
    t = numpy.r_[0, t]

    return triangular_mesh(x, y, z, triangles, scalars=t)
```

When I change the title to `1`, only a dot shows up in the plot:

```python
test_triangular_mesh()
title("1")
```

Long words are the same:
```python
test_triangular_mesh()
title("Iteration")
```

The n is not correctly rendered.

**Comment by stefanoborini** [comment] 2016-04-04 15:01
Cannot reproduce as of today, either on OSX or Linux. While the font is definitely not the best available (bad kerning, but I doubt is a problem at the mayavi level) every letter is present and readable. Closing

**Closed by stefanoborini** 2016-04-04 15:01 UTC
