### ISSUE TITLE
Control which side of the plot is facing

### ISSUE THREAD

**Issue by jierice** [enthought/mayavi#545] opened 2017-08-11 14:31 UTC
I am wondering is there a way to control which side of the mayavi plot is facing. For example, can I plot an image facing downward? It doesn't matter normally. Because you will be able to see the plot from both sides. But if you want to export to vrml(a 3d printing format). It will be a problem.

**Comment by prabhuramachandran** [comment] 2017-08-11 15:34
You can set the camera position using ``mlab.view`` and orient the plot the way you want to. See: http://docs.enthought.com/mayavi/mayavi/auto/mlab_camera.html?highlight=view#mayavi.mlab.view

I am not sure if this does what you want.  If this is not a bug I would prefer to close the issue, for questions please ask on mayavi-users or on ets-users.  Please reopen if you think there is a bug though. Thank you!

**Closed by prabhuramachandran** 2017-08-11 15:34 UTC
