### ISSUE TITLE
Control+C with Mayavi import exits python

### ISSUE THREAD

**Issue by fnielsen** [enthought/mayavi#171] opened 2015-04-15 17:02 UTC
After import of mayavi.mlab the Control+C exits python with no KeyboardInterrupt. Example:

    $ python
    Python 2.7.3 (default, Dec 18 2014, 19:10:20) 
    [GCC 4.6.3] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import mayavi.mlab
    >>>           # here I press Control+C
    $ 

Is this really an intended behavior?

This is not a problem with matplotlib:

    $ python
    Python 2.7.3 (default, Dec 18 2014, 19:10:20) 
    [GCC 4.6.3] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import matplotlib.pyplot as plt
    >>>          # here I press Control+C
    KeyboardInterrupt
    >>>

**Comment by stefanoborini** [comment] 2016-04-27 13:48
Cannot reproduce. Probably no longer relevant? 
```
$ python
Python 2.7.10 |jaguar 3.0.0.dev635 (x86_64)| (default, Nov 11 2015, 02:18:41) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-55)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from mayavi import mlab
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> 
```
Closing

**Closed by stefanoborini** 2016-04-27 13:48 UTC

**Comment by fnielsen** [comment] 2016-05-02 09:50
I can confirm that there is no longer a problem after an upgrade to version 4.4.4.  I see the same behaviour as @stefanoborini.

**Comment by stefanoborini** [comment] 2016-05-03 08:10
@fnielsen thank you.
