### ISSUE TITLE
Opacity issues

### ISSUE THREAD

**Issue by Jellby** [enthought/mayavi#574] opened 2017-12-09 18:44 UTC
It is common to see artifacts in translucent object in any 3D rendering software, but I wonder if there is something that could be done to alleviate them in Mayavi. I took the ["atomic orbital" example](http://docs.enthought.com/mayavi/mayavi/auto/example_atomic_orbital.html), added `opacity=0.8`, and this more or less shows the issue, as I slightly tilt the object from left to right:
![snapshot2](https://user-images.githubusercontent.com/7943459/33798424-410cdbb6-dd18-11e7-8649-19a0a83ea9e3.png)
The center figure shows obvious artifacts, but it is also clear (at least when seeing it "live") that there is something wrong in the right figure: for instance, the pink-blue part of the surface should stay at the top right, and not the top left.

I also see things similar to [this](http://vtk.1045678.n5.nabble.com/slicing-artifact-when-rendering-semi-transparent-mesh-td5743682.html), and it is suggested that "[depth peeling](https://www.vtk.org/Wiki/VTK/Depth_Peeling)" could help. Can I enable it with Mayavi? How?

**Comment by larsoner** [comment] 2018-05-02 19:48
I tried for a while to get depth peeling to work by digging into `tvtk` and even `vtk` itself but was never able to. :(

**Comment by prabhuramachandran** [comment] 2018-08-26 21:03
I tried this:
```
s = mlab.pipeline.surface(contour2, colormap='hsv', opacity=0.8)
s.scene.renderer.use_depth_peeling = True
```
And it seems to look pretty good to me with VTK 8.1.1.  Also you could try increasing 
```
s.scene.renderer.maximum_number_of_peels = 8
```
I am unable to reproduce this so am closing this for now.  Please reopen if you are running into issues.

**Closed by prabhuramachandran** 2018-08-26 21:03 UTC
