### ISSUE TITLE
Error in vtkExecutive.cxx and segmentation fault when running "Pick on the surface" example

### ISSUE THREAD

**Issue by hakonhagland** [enthought/mayavi#141] opened 2014-09-12 06:35 UTC
Hi I just started to explore MayaVi2. When running "Pick on the surface" [example](http://docs.enthought.com/mayavi/mayavi/auto/example_pick_on_surface.html#example-pick-on-surface) I get the following errors after clicking the surface:

```
Data indices: 82, 20
ERROR: In /build/buildd/vtk-5.8.0/Filtering/vtkExecutive.cxx, line 756
vtkStreamingDemandDrivenPipeline (0xb976b50): Algorithm vtkAssignAttribute(0xb976068) returned failure for request: vtkInformation (0xb49e8c8)
  Debug: Off
  Modified Time: 866568
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0



ERROR: In /build/buildd/vtk-5.8.0/Filtering/vtkExecutive.cxx, line 756
vtkStreamingDemandDrivenPipeline (0xa9d7300): Algorithm vtkAssignAttribute(0xa9d66e8) returned failure for request: vtkInformation (0xa5a51b8)
  Debug: Off
  Modified Time: 867490
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0



Segmentation fault (core dumped)
```

I am using MayaVi2 version 4.1.0 on Ubuntu 14.04 on i686 and Python version 2.7.6.

**Comment by stefanoborini** [comment] 2016-03-31 11:03
cannot reproduce with vtk 6.3, so probably it was a vtk bug that got fixed. Closing.

**Closed by stefanoborini** 2016-03-31 11:03 UTC
