### ISSUE TITLE
Assigning custom colormap to volumes does not work

### ISSUE THREAD

**Issue by isomerase** [enthought/mayavi#371] opened 2016-04-29 21:50 UTC
I am trying to apply the demo code for [creating custom colormaps](http://docs.enthought.com/mayavi/mayavi/auto/example_custom_colormap.html#example-custom-colormap) to the [demo code for volumetric data](http://docs.enthought.com/mayavi/mayavi/mlab.html#visualizing-volumetric-scalar-data) (i.e. apply custom colormap to a volume rather than a surface):

```
import numpy as np
from mayavi import mlab
mlab.figure(bgcolor=(1, 1, 1))

x, y, z = np.ogrid[-10:10:20j, -10:10:20j, -10:10:20j]
s = np.sin(x*y*z)/(x*y*z)

src = mlab.pipeline.scalar_field(s)
vol = mlab.pipeline.volume(src)

# Retrieve the LUT of the volume object.
lut = vol.module_manager.scalar_lut_manager.lut.table.to_array()
lut[:, -1] = np.linspace(0, 255, 256)
vol.module_manager.scalar_lut_manager.lut.table = lut

# We need to force update of the figure now that we have changed the LUT.
mlab.draw()
mlab.show()

```
However, the colormap remains unchanged. Try as I might, the line `vol.module_manager.scalar_lut_manager.lut.table = lut` has no effect.

This bug seems to be affecting a [few](https://stackoverflow.com/questions/26970659/scalar-fields-visualisation-in-python) [people](https://stackoverflow.com/questions/36946231/using-perceptually-uniform-colormaps-in-mayavi-volumetric-visualization)

**Comment by stefanoborini** [comment] 2016-05-03 16:11
I've already seen something like this...

**Comment by stefanoborini** [comment] 2016-05-03 16:17
Could be related to #262, which has been fixed in master, but I am not sure.

**Comment by prabhuramachandran** [comment] 2016-07-27 04:10
Well, this is not a bug.  A volume does not use the standard scalar lut manager and instead uses a color transfer function which maps scalars to colors.  To manipulate this is a bit tricky but there are a few utility functions that should make it much easier.  Here is a modified example:

```
import numpy as np
from mayavi import mlab
mlab.figure(bgcolor=(1, 1, 1))

x, y, z = np.ogrid[-10:10:20j, -10:10:20j, -10:10:20j]
s = np.sin(x*y*z)/(x*y*z)

src = mlab.pipeline.scalar_field(s)
vol = mlab.pipeline.volume(src)

# Change the color transfer function
from tvtk.util import ctf
c = ctf.save_ctfs(vol._volume_property)
print c
c['alpha'][1][1] = 1.0
ctf.load_ctfs(c, vol._volume_property)
# Update the shadow LUT of the volume module.
vol.update_ctf = True

mlab.show()
```
The key here is the `save_ctfs` and `load_ctfs`.  You can look at https://github.com/enthought/mayavi/blob/master/tvtk/util/ctf.py if you want to understand this a bit better.  All the example above does is to manipulate the opacity transfer function and set it back on the volume property.

I am closing this as this is not a bug.

**Closed by prabhuramachandran** 2016-07-27 04:10 UTC
Labels: bug
