### ISSUE TITLE
SetActiveAttribute filter failure with legacy VTK files (Mayavi 4.4.3)

### ISSUE THREAD

**Issue by rc** [enthought/mayavi#380] opened 2016-05-04 12:25 UTC
Hi,

I have an issue with Mayavi 4.4.3 in kubuntu 16.04, related to using the SetActiveAttribute filter. The following used to work up to 4.3(? - tested on 4.1, but the other probably related error described below has been reported only with 4.4.) :

1. run mayavi: ``mayavi2 cylinder.vtk``
2. add SetActiveAttribute to the VTK file source.

Now the step 2 fails with:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mayavi/core/source.py", line 216, in _handle_children
    obj.start()
  File "/usr/lib/python2.7/dist-packages/mayavi/core/filter.py", line 108, in start
    self.update_pipeline()
  File "/usr/lib/python2.7/dist-packages/mayavi/filters/set_active_attribute.py", line 133, in update_pipeline
    self._update()
  File "/usr/lib/python2.7/dist-packages/mayavi/filters/set_active_attribute.py", line 150, in _update
    pnt_attr, cell_attr = get_all_attributes(input)
  File "/usr/lib/python2.7/dist-packages/mayavi/sources/vtk_xml_file_reader.py", line 86, in get_all_attributes
    point_attr = get_attribute_list(obj.point_data)
AttributeError: 'AlgorithmOutput' object has no attribute 'point_data'
```

I came on this when debugging why sfepy's custom mayavi-based viewer fails with the version 4.4. There, the error is probably related:

```
osboxes@osboxes:~/sfepy$ ./postproc.py cylinder.vtk 
pci id for fd 3: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
sfepy: point vectors u at [-0.05 -0.02  0.  ]
sfepy: range: -1.45e-03 1.00e-02 l2 norm range: 0.00e+00 1.01e-02
No handlers could be found for logger "mayavi.core.common"
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f67c49e8ad0>, trait: activated, old value: <undefined>, new value: True
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/home/osboxes/sfepy/sfepy/postprocess/viewer.py", line 1216, in _post_init
    viewer.render_scene(self.scene, viewer.options)
  File "/home/osboxes/sfepy/sfepy/postprocess/viewer.py", line 686, in render_scene
    self.build_mlab_pipeline(**options)
  File "/home/osboxes/sfepy/sfepy/postprocess/viewer.py", line 555, in build_mlab_pipeline
    active = mlab.pipeline.set_active_attribute(source)
  File "/usr/lib/python2.7/dist-packages/mayavi/tools/pipe_base.py", line 38, in the_function
    factory = factory_class(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mayavi/tools/pipe_base.py", line 163, in __init__
    self.set(**traits)
  File "/usr/lib/python2.7/dist-packages/mayavi/tools/pipe_base.py", line 180, in set
    self._anytrait_changed(trait, value)
  File "/usr/lib/python2.7/dist-packages/mayavi/tools/pipe_base.py", line 198, in _anytrait_changed
    setattr(obj, components[-1], value)
  File "/usr/lib/python2.7/dist-packages/mayavi/core/trait_defs.py", line 101, in set_value
    value )
TraitError: The 'point_vectors_name' trait of a SetActiveAttribute instance must be one of [], but a value of '' <type 'str'> was specified.
```

-> it seems there are no point_data in the dataset (but there are...).

Best regards,
r.

**Comment by prabhuramachandran** [comment] 2016-07-27 03:35
Hi @rc,  I am not able to reproduce this. I suspect this has since been fixed in Mayavi. I tried with VTK's `blow.vtk` example data and this seems to work without error.  Could you try with master and see if this now works?  Thanks.

**Comment by prabhuramachandran** [comment] 2016-08-01 20:14
@rc -- 4.5.0 is now live on pypi, if you can please test with that and update this issue, that would be great.  I am closing this ticket for now, please feel free to reopen if it is not fixed.  Thanks!

**Closed by prabhuramachandran** 2016-08-01 20:14 UTC

**Comment by rc** [comment] 2016-08-22 13:05
Hi @prabhuramachandran, thanks for the response. What is the best way to install mayavi 4.5.0 into a virtual environment on a linux machine? VTK is not on pypi, right?

**Comment by prabhuramachandran** [comment] 2016-08-23 09:41
Hi @rc -- VTK is not on PyPI but I imagine you can just use the standard VTK that is already on your system.  Mayavi 4.5.0 should work just fine with that.  What I usually do is create a `virtualenv --system-site-packages` and then just do `pip install -U mayavi` in there.

**Comment by rc** [comment] 2016-08-24 09:15
Thanks for the advice! I have installed mayavi using

```
virtualenv --system-site-packages venv
source venv/bin/activate
python -V
pip install -U envisage
pip install -U mayavi
mayavi2 --version
```

and both `mayavi2 cylinder.vtk` and `mayavi2 blow.vtk` work, so the installation is probably OK.

But the error reported above persists and occurs also with `blow.vtk`, although the exception message is different. After adding `SetActiveAttribute` filter, a popup message appears with a traceback, that is also printed on the terminal:

```
Traceback (most recent call last):
  File "/home/user/tmp/venv/local/lib/python2.7/site-packages/mayavi/core/source.py", line 216, in _handle_children
    obj.start()
  File "/home/user/tmp/venv/local/lib/python2.7/site-packages/mayavi/core/filter.py", line 108, in start
    self.update_pipeline()
  File "/home/user/tmp/venv/local/lib/python2.7/site-packages/mayavi/filters/set_active_attribute.py", line 133, in update_pipeline
    self._update()
  File "/home/user/tmp/venv/local/lib/python2.7/site-packages/mayavi/filters/set_active_attribute.py", line 149, in _update
    input.update()
AttributeError: 'AlgorithmOutput' object has no attribute 'update'
```

FWIW, when I close the popup, there are no data names in the `SetActiveAttribute` filter in the GUI.

Can you reproduce that? I can provide versions of other packages mayavi depends on, it that would help.

Best regards,
r.

**Comment by prabhuramachandran** [comment] 2016-08-29 20:15
@rc -- I am unable to reproduce this with master.  But that is somewhat besides the point as are you using VTK 6.x or 5.x?  I suspect you are using 5.x?  Is this correct?  What version of VTK are you using.  I can send a fix for this.

**Comment by rc** [comment] 2016-09-02 13:24
Yes, @prabhuramachandran, I have VTK 5.8.

**Comment by mattions** [comment] 2017-05-29 11:26
I know this is a closed issues, however we are hitting exactly the same error in the linked issue: https://github.com/mattions/neuronvisio/issues/64

We are using this packages:

```
mayavi=4.5.0=py27_0
vtk=6.3.0=py27_1
```

Is there a way to test if it is an installation problem or something else?

Thanks.
